remacs/remacs

lisp/Makefile.in, lisp/loadup.el, nextstep/Makefile.in, src/Makefile.in
Thanks for this fork! 
also if there's a checklist I should run through before submitting a pr, let me know, I didn't see one in the readme.
=> emacs >> remacs

README.md, lisp/startup.el
I haven't even gotten to the Rust part yet..
Not sure how deep you want to go replacing `Emacs` with `Remacs`, but this is a start.
=> Change welcome message to 'Remacs'

Makefile.in, lisp/Makefile.in
This is the fix for Issue #20.
=> Added .elc files to the list of files that get removed by 'make clean'.

src/nsfns.m, src/nsmenu.m, src/nsterm.h, src/nsterm.m
Should fix #47.
@rogermarlow would you mind confirming this looks good?
=> Fix macOS 12 deprecation notices

configure.ac
=> Add rust winapi dependencies.

rust_src/src/atom.rs, rust_src/src/cons.rs, rust_src/src/floatfns.rs, rust_src/src/lib.rs, rust_src/src/lisp.rs, rust_src/src/math.rs, rust_src/src/strings.rs, rust_src/src/symbols.rs, src/floatfns.c
work in progress still, just want to open this to track progress and get any early feedback if anyone is feeling generous!
=> adding some new float functions

README.md
This has caused some confusion, so I thought it would be worth showing an example.
=> Rust tutorial: exposing functions to the C code

.travis.yml, rust_src/Cargo.toml, rust_src/src/lib.rs, src/data.c, src/floatfns.c
=> Silence warnings and enforce a clean Rust build

.travis.yml, configure.ac
Enforce --features="strict" in travis via configure script rather than an explicit duplicate cargo build step
=> Use cargo flags for features flag

src/callproc.c, src/fileio.c, src/term.c
=> Fix windows compile error.

.travis.yml, rust_src/src/lib.rs, rust_src/src/strings.rs, src/fns.c
Rebased #106, plus running tests without parallelism.
=> Base64 decode

.travis.yml, rust_src/src/lib.rs, test/lisp/autorevert-tests.el, test/lisp/dired-tests.el, test/lisp/progmodes/flymake-tests.el
=> Build on OS X too

.travis.yml, rust_src/alloc_unexecmacosx/src/lib.rs, rust_src/src/base64.rs, rust_src/src/lisp.rs
#144 rebased on latest master.
=> Run rustfmt on Travis

autogen.sh
Just noted it when building the first time again :+1: 
=> Change Emacs to Remacs in autogen.sh

rust_src/src/eval.rs
=> Add ! as return type for xsignal

rust_src/remacs-lib/README.md
New contributors should be able to read this README to fully understand what code should live in remacs-lib.
=> Adding a README.md to better explain the purpose of the remacs-lib 

rust_src/remacs-macros/README.md
While reading through docs I found a duplicate sentence.
=> removed duplicate sentence in remacs-macros/README

CONTRIBUTING.md
Hi @birkenfeld 
I've added you to the list of collaborators, so I thought you should be on the list of people who can review code. No obligation -- review as little or as much as you wish :)
=> Mention @birkenfeld

REMACS_COMPATIBILITY.md, rust_src/Cargo.lock, rust_src/Cargo.toml, rust_src/src/base64.rs, rust_src/src/lib.rs, rust_src/src/multibyte.rs, rust_src/src/strings.rs, test/lisp/net/sasl-scram-rfc-tests.el
=> Move from (deprecated) rustc-serialize to base64 crate

rust_src/src/lib.rs, rust_src/src/lisp.rs, rust_src/src/marker.rs, rust_src/src/math.rs, src/marker.c
Rebased version of #292 to fix conflicts.
=> Marker position

rust_src/remacs-sys/lib.rs, rust_src/src/data.rs, rust_src/src/lib.rs, src/data.c
=> implement both C indirect-function and lisp one

rust_src/remacs-sys/lib.rs, rust_src/src/lib.rs, rust_src/src/multibyte.rs, rust_src/src/symbols.rs, src/data.c
Bit fields manipulations are hacky
=> Port keywordp to rust

rust_src/remacs-sys/lib.rs, rust_src/src/lib.rs, rust_src/src/windows.rs, src/window.c
=> Ported minibuffer-selected-window

rust_src/remacs-sys/lib.rs, rust_src/src/buffers.rs, rust_src/src/crypto/mod.rs
=> Fix TODO: buffer*

configure.ac
Fixes https://github.com/Wilfred/remacs/issues/370
=> Fixing build issue for Arch linux, where there was a missing -lm

lib-src/emacsclient.c
This is a change in the C code, but I get bitten by this often enough to bother making this change
=> Make remacsclient -a "" start the remacs daemon

rust_src/remacs-sys/lib.rs, rust_src/src/lib.rs, rust_src/src/lisp.rs, rust_src/src/minibuf.rs, src/minibuf.c
Make `minibuf_window` mutable.
Add `as_minibuffer_or_error()`
Closes #389
=> Port set-minibuffer-window

src/fns.c
Fixes https://github.com/Wilfred/remacs/issues/408
=> Fixing minor warning in fns.c introduced in recent PR.

rust_src/remacs-sys/lib.rs, rust_src/src/indent.rs, rust_src/src/lib.rs, src/indent.c
Had to expose C current_column for this to work.
Closes #327
=> Port current-column

rust_src/src/editfns.rs, rust_src/src/lib.rs, src/editfns.c
=> Port position-bytes to Rust

.travis.yml
Didn't read the build output carefully enough.
=> Clean up the mess left in travis.yml.

rust_src/remacs-sys/lib.rs, rust_src/src/lib.rs, rust_src/src/lisp.rs, rust_src/src/symbols.rs, src/data.c
=> Implement symbol-value.

rust_src/src/lib.rs, rust_src/src/lisp.rs, rust_src/src/process.rs, src/process.c
I had to include the s/from_raw/raw/ to test - let me know whether to take them out.
I wasn't really sure whether to go with an is_list, or reuse listp.
#354
=> Set process plist

.travis.yml, README.md, rust_src/src/lisp.rs
=> Bump rustfmt version.

rust_src/src/frames.rs, rust_src/src/lib.rs, rust_src/src/lisp.rs
=> Allow defsubr to be used per file.

rust_src/src/lib.rs, rust_src/src/windows.rs, src/window.c
Added LispWindowRef::is_internal as well.
Closes #396
=> Post window-combination-limit and set-window-combination-limit

.travis.yml
It is currently set to ignore failures.
=> Add a no window build and test

rust_src/remacs-sys/lib.rs, rust_src/src/eval.rs, rust_src/src/keyboard.rs, rust_src/src/keymap.rs, rust_src/src/lisp.rs, rust_src/src/lists.rs, src/keyboard.c, src/keymap.c
Along the way, add a message_with_string macro, and an Iterator that walks
the cars of a cons object.
=> Port lookup-key and lucid_event_type_list_p

rust_src/src/buffers.rs, rust_src/src/editfns.rs, src/editfns.c
=> Porting gap-position and gap-size to Rust

README.md
This isn't a perfect example, because we now have `LispObject::as_cons` which provides a safe API. Still, I think it illustrates the principle, and it's better than it was before.
Suggestions for better examples of genuine uses of pointer manipulation are welcome :)
=> Update readme example to use latest LispObject APIs

rust_src/src/lisp.rs, rust_src/src/multibyte.rs, rust_src/src/obarray.rs, rust_src/src/process.rs, rust_src/src/symbols.rs, rust_src/src/threads.rs, rust_src/src/vectors.rs, rust_src/src/windows.rs
=> Further work on removing references to ExternalPtr refs

CONTRIBUTING.md, CONTRIBUTORS
Add a pitfall section as well.
Add a new CONTRIBUTORS file.
=> Update CONTRIBUTING docs with a style guide

.travis.yml
Added missing travis script line
=> Added missing travis os x line

README.md
add readme about outdated makeinfo on macOS.
#361
=> add readme about outdated makeinfo on macOS

rust_src/remacs-sys/lib.rs, rust_src/src/buffers.rs, src/buffer.c
=> port barf-if-buffer-read-only

rust_src/remacs-sys/lib.rs, rust_src/src/cmds.rs, src/cmds.c
This should take care of #406.
=> Port forward-line to Rust

docker-compose.yml
=> Fix Dockerfile location in docker-compose

rust_src/src/frames.rs
=> as_lisp_obj should return a tagged pointer for LispFrameRef

rust_src/src/frames.rs
Break the core logic of `framep` out into a separate function. Use
this function internally since we already have `LispFrameRef` objects.
This allows `frame_live_p` to not duplicate the frame checks again in
`framep`.
`window-system` should just return a `LispObject`. There is no reason
to convert to a Symbol and immediately turn it back into a
`LispObject`.
=> Refactor frame handling

src/Makefile.in
=> Declare globals.h a dependency of the Rust build

rust_src/src/eval.rs, rust_src/src/lisp.rs, src/eval.c, src/lread.c, test/rust_src/src/eval-tests.el
=> Port 'function'

rust_src/remacs-sys/lib.rs, rust_src/src/eval.rs, src/eval.c, test/rust_src/src/eval-tests.el
=> Port commandp

rust_src/remacs-sys/lib.rs, rust_src/src/windows.rs, src/window.c, src/window.h
=> port set-window-parameter

rust_src/src/data.rs, rust_src/src/eval.rs, rust_src/src/lisp.rs, rust_src/src/symbols.rs, src/eval.c, test/rust_src/src/eval-tests.el
=> Port FUNCTIONP and Ffunctionp

rust_src/Cargo.lock, rust_src/Cargo.toml, rust_src/build.rs, rust_src/remacs-sys/lib.rs, rust_src/src/eval_macros.rs, rust_src/src/lisp.rs
Simpler code.
Supports GC protected statics.
Enable clippy for build script
=> Refactor buid.rs

rust_src/src/windows.rs
=> typo fixes for `wants_header_line`

rust_src/remacs-sys/lib.rs, rust_src/src/windows.rs, src/dispextern.h, src/window.c, src/window.h
Also CURRENT_MODE_LINE_FACE_ID and CURRENT_MODE_LINE_FACE_ID_3
Replace the original macros with extern references.
=> Port CURRENT_MODE_LINE_HEIGHT

rust_src/src/process.rs, src/process.c
=> Port waiting-for-user-input-p

autogen.sh
=> Don't tell users to override the Rust toolchain to nightly.

rust_src/src/data.rs, rust_src/src/lisp.rs, src/data.c, src/marker.c, test/rust_src/src/data-tests.el
=> Port subr-arity and subr-name

rust_src/remacs-macros/function.rs
rather than a syn::Path argument. No effects on the generated code are intended.
=> Minor refactor: make is_lisp_object take a syn::Type argument

.travis.yml, configure.ac, rust_src/remacs-macros/function.rs
I introduced a compiler warning, which this PR fixes.
I don't understand why it passed the tests, though. Should there be a `strict` feature in `remacs-macros/Cargo.toml`?
=> Fix a compiler warning.

rust_src/src/fns.rs, rust_src/src/remacs_sys.rs, src/fns.c
usage: (append &rest SEQUENCES)
=> port the append function to rust

doc/lispref/strings.texi, etc/NEWS, etc/NEWS.26, lisp/emacs-lisp/byte-opt.el, lisp/emacs-lisp/easy-mmode.el, lisp/register.el, lisp/simple.el, lisp/term/ns-win.el, lisp/textmodes/page-ext.el, lisp/xdg.el, m4/sys_types_h.m4, src/gtkutil.c, src/lcms.c, test/data/xdg/mimeapps.list, test/data/xdg/mimeinfo.cache, test/lisp/net/tramp-tests.el, test/lisp/vc/smerge-mode-tests.el, test/lisp/xdg-tests.el, test/src/lcms-tests.el
#727 was a little too big for one merge, so whilst the notes are useful, I'm going to do a few smaller merges instead.
=> Merge more commits from GNU Emacs master branch

rust_src/src/fns.rs, src/fns.c
usage: (concat &rest SEQUENCES)
=> port the DEFUN concat of fns.c

rust_src/admin/build-and-run-remacs.sh, rust_src/admin/did-it-work.sh
Use like this. Pay attention to the escaping!!
$ pwd
/path/to/top/of/remacs/tree
$ git bisect start
$ git bisect good @{"2 weeks ago"}  # last time you know it worked
$ git bisect bad HEAD               # top of current tree
$ git bisect run rust_src/admin/did-it-work.sh -Q --eval "\"(some-lisp)\""
Each iteration the script will build remacs and run it with the arguments
provided. Exit emacs if possible or Control-C it from the terminal. You
will then be asked "Did it work?". Press Y or N and enter. Git will find
the first broken commit if possible.
The broken commit hash will be output by Git if it found it. Run git bisect
reset when you are done and the tree will be back to where you started. git
checkout ABC123 # the bad hash will set the tree to the first broken
version so you can …
=> Add tools for git bisect

CONTRIBUTING.md, rust_src/README.md
@shaleh, are there any other places in the documentation that mention the old API, that you're aware of?
=> Adjust documentation for Lisp*Object merge

configure.ac, src/Makefile.in
=> rearrange the order of objects when linking temacs

rust_src/src/casetab.rs, rust_src/src/lib.rs, src/casetab.c, test/rust_src/src/casetab-tests.el
=> Port case-table-p

lisp/loadup.el
We're creating a binary called 'remacs' at this point.
=> Correcting the filename in the dump message

rust_src/src/windows.rs, src/window.c, test/rust_src/src/windows-tests.el
Port `window-dedicated-p` and `set-window-dedicated-p`.
Closed #746
=> Port window-dedicated-p and set-window-dedicated-p

rust_src/src/windows.rs, src/window.c, test/rust_src/src/windows-tests.el
=> Port window-old-point

configure.ac
=> Remove zlib option in configure.ac

rust_src/src/marker.rs, rust_src/src/remacs_sys.rs, src/alloc.c, src/editfns.c
=> Port point-marker, point-min-marker, and point-max-marker.

rust_src/src/data.rs
=> Fix store_symval_forwarding().

rust_src/src/cmds.rs
=> Fix internal_self_insert().

rust_src/src/dired.rs, rust_src/src/dired_unix.rs, rust_src/src/dired_windows.rs, src/dired.c
On Unix it's all Rust here except for some support functionality.
On Windows all C except for entry point.
=> Rust port of directory-files

rust_src/src/floatfns.rs, test/rust_src/src/floatfns-tests.el
=> Fix float division by zero

rust_src/src/decompress.rs, test/rust_src/src/decompress-tests.el
=>  Fix panic when decompressing empty buffer region

lisp/emacs-lisp/find-func.el, test/rust_src/src/data-tests.el
This fixes one of the problems from https://github.com/Wilfred/remacs/issues/876. The other is addressed by https://github.com/Wilfred/remacs/pull/879.
=> Find rust variables

.travis.yml, configure.ac, src/dispextern.h, src/dispnew.c, src/doprnt.c, src/fileio.c, src/frame.c, src/frame.h, src/keyboard.c, src/menu.c, src/menu.h, src/term.c, src/w32fns.c, src/window.c, src/xdisp.c, src/xfaces.c, src/xfns.c, src/xmenu.c, src/xrdb.c, src/xsettings.c, src/xsettings.h, src/xterm.c, src/xterm.h
=> delete `lucid` and `motif` x-toolkits

rust_src/src/lib.rs, rust_src/src/search.rs, src/lisp.h, src/search.c, test/lisp/help-fns-tests.el
Nothing too complicated here, but reviewers might double check to make sure I didn't copy-paste the wrong docstrings or something.
=> Port search wrapper defuns

src/xfns.c, src/xmenu.c, src/xsmfns.c, src/xterm.c
After merging #885 and #910 , non-gtk logic isn't needed in x related files.
=> delete more non-gtk code in x related files.

rust_src/src/buffers.rs, rust_src/src/character.rs, rust_src/src/floatfns.rs, rust_src/src/fonts.rs, rust_src/src/frames.rs, rust_src/src/hashtable.rs, rust_src/src/keymap.rs, rust_src/src/lisp.rs, rust_src/src/lists.rs, rust_src/src/marker.rs, rust_src/src/multibyte.rs, rust_src/src/numbers.rs, rust_src/src/process.rs, rust_src/src/symbols.rs, rust_src/src/threads.rs, rust_src/src/vectors.rs, rust_src/src/windows.rs
=> remove inline attributes

rust_src/src/fileio.rs, src/fileio.c
Fixes #927.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wilfred/remacs/961)
=> Port clear-buffer-auto-save-failure

README.md
Move porting related sections.
=> move sections in the readme

rust_src/src/dispnew.rs, rust_src/src/lib.rs, rust_src/src/remacs_sys.rs, rust_src/src/terminal.rs, src/dispnew.c, src/terminal.c
I'm not too sure if I got the `unsafe fn` attributes right.
Closes #929.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wilfred/remacs/962)
=> Port redraw-frame, redraw-display, and associated C functions

rust_src/src/windows.rs, src/window.c, test/rust_src/src/windows-tests.el
=> Port window-new-total to Rust.

.travis.yml, configure.ac, src/alloc.c, src/buffer.c, src/casetab.c, src/data.c, src/editfns.c, src/frame.h, src/keymap.c, src/lisp.h, src/minibuf.c, src/process.c, src/process.h, src/window.c, src/window.h, src/xterm.c
This is mostly adding missing prototypes, fixing https://github.com/Wilfred/remacs/issues/957.
=> Address C compiler warnings

rust_src/src/buffers.rs, rust_src/src/crypto/mod.rs, rust_src/src/editfns.rs, rust_src/src/marker.rs, rust_src/src/minibuf.rs, rust_src/src/process.rs, rust_src/src/remacs_sys.rs
*Note*
Has bugs, this is for review of the style and naming.
=> Alternative LispBufferOrName implementation.

rust_src/src/dispnew.rs, rust_src/src/windows.rs, src/dispnew.c, src/window.c
Closes #974.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wilfred/remacs/979)
=> Port internal-show-cursor{,-p}

rust_src/src/dispnew.rs
=> Add in 'min' requirement.

rust_src/src/editfns.rs, src/editfns.c, test/rust_src/src/editfns-tests.el
=> Port buffer string

rust_src/src/fonts.rs, src/font.c
=> [WIP] Port font-match-p.

rust_src/src/syntax.rs, src/syntax.c
Address #969.
I'm watching #985 with great interest as well.
=> Port standard-syntax-table.

rust_src/src/fileio.rs, src/fileio.c
=> [#1006] port recent-auto-save-p

rust_src/src/callint.rs, rust_src/src/lib.rs, src/callint.c
More important than this particular function (which has no body at
all) is setting up the callint module in Rust.
=> "Port" interactive defun

rust_src/src/frames.rs, rust_src/src/windows.rs, src/window.c, src/window.h
@nickdrozd gave me an intro to porting functions to rust for remacs (thanks! ^_^)
Rust changes have been formatted with rustfmt.
=> port select-window

rust_src/src/syntax.rs, src/syntax.c, src/syntax.h
I don't know how to handle `Vstandard_syntax_table`.
=> port copy-syntax-table

rust_src/src/buffers.rs, test/rust_src/src/buffers-tests.el
=> Refresh the port of buffer-list.

rust_src/src/frames.rs, src/frame.c
This PR contains the functions of #946 that don't need special treatment. I open a separate PR so I can take the time to find a solution.
=> trivial frame funcs

rust_src/src/buffers.rs
Only found this because I started to use remacs :P
=> add intspec to erase_buffer

rust_src/src/casefiddle.rs, rust_src/src/cmds.rs, rust_src/src/data.rs, rust_src/src/eval.rs, rust_src/src/fns.rs, rust_src/src/fonts.rs, rust_src/src/hashtable.rs, rust_src/src/keymap.rs, rust_src/src/lists.rs, rust_src/src/lread.rs, rust_src/src/obarray.rs, rust_src/src/symbols.rs, src/data.c
I'd like to port the  C function `harmonize_variable_watchers` too, but it does some weird stuff I don't understand.
=> Port variable watcher functions

CONTRIBUTORS
IMO we don't need this file. Last commit was almost 1 year ago.
=> remove CONTRIBUTORS file

rust_src/src/data.rs, rust_src/src/editfns.rs, rust_src/src/eval.rs, rust_src/src/fns.rs, rust_src/src/frames.rs, rust_src/src/keymap.rs, rust_src/src/lread.rs, rust_src/src/obarray.rs
This allows for doing away with some unsafe blocks.
=> Fcons -> LispObject::cons

rust_src/src/lists.rs, rust_src/src/multibyte.rs, rust_src/src/vectors.rs, src/fns.c, src/lisp.h
Along the way refactor bool vector iterator.
This is a simpler PR than @birkenfeld's original. Whenever I switch
to `iter().collect()` I get failures and crashes. This code is a
reasonable starting point at least.
=> Port mapcar1.

README.md
close  #886
I don't have a mac, so I have no idea what I'm adding here ;)
If anything needs to be changed just push to this branch.
=> update macos requirements

rust_src/src/keymap.rs, src/keymap.c, src/keymap.h, test/rust_src/src/keymap-tests.el
Thanks @accidentalrebel for your work.
=> Port copy-keymap

rust_src/src/eval.rs, src/eval.c, test/rust_src/src/eval-tests.el
Fixes https://github.com/Wilfred/remacs/issues/989
=> Port catch

rust_src/src/data.rs, rust_src/src/lread.rs, rust_src/src/multibyte.rs, rust_src/src/remacs_sys.rs
=> Replace emacs_abort with panic!

rust_src/src/syntax.rs, src/syntax.c
Hi. I’m interested in this project and try to contribute!
This should resolve #1078
=> Porting syntax-table-p

README.md
[#886](https://github.com/Wilfred/remacs/issues/886)
=> Updated Mojave build instructions for libxml2

rust_src/src/buffers.rs, rust_src/src/lib.rs, rust_src/src/vectors.rs, rust_src/src/window_configuration.rs, rust_src/src/windows.rs, src/window.c, src/window.h, test/rust_src/src/window_configuration-tests.el
DEFUNs
- window-configuration-p
- window-configuration-frame
- compare-window-configurations
C function
- compare_window_configurations
Adds SaveWindowDataRef and SavedWindowRef which both implement an `equal`
method.
=> Port window configuration support.

autogen.sh, docker/Dockerfile.in, docker/build-it.sh, docker/fedora/Dockerfile, docker/run-it.sh, docker/ubuntu/32bit/Dockerfile, docker/ubuntu/Dockerfile, docker/ubuntu/cosmic/Dockerfile, docker/ubuntu/cosmic/config.yaml, rust_src/Cargo.toml
The build succeeds. However, `make check` fails on the Rust portion.
The `miniz-sys` crate fails to compile.
=> Add Ubuntu Cosmic support to Docker files.

rust_src/src/windows.rs, src/window.c, test/rust_src/src/windows-tests.el
=> Port set-window-new-total

rust_src/src/coding.rs, rust_src/src/lib.rs, src/coding.c, test/rust_src/src/coding-tests.el
Hi! I ported `coding-system-p`. This PR will close #1100.
=> Port coding-system-p

rust_src/src/buffers.rs, rust_src/src/chartable.rs, rust_src/src/data.rs, rust_src/src/eval.rs, rust_src/src/eval_macros.rs, rust_src/src/fns.rs, rust_src/src/frames.rs, rust_src/src/lists.rs, rust_src/src/lread.rs, rust_src/src/marker.rs, rust_src/src/multibyte.rs, rust_src/src/obarray.rs, rust_src/src/process.rs, rust_src/src/strings.rs, rust_src/src/symbols.rs, rust_src/src/threads.rs, rust_src/src/vectors.rs, rust_src/src/windows.rs
Prefer into where possible, or else LispObject::from
=> Cut as_lisp_obj

rust_src/src/base64.rs
When we're told decode into a multibyte string, we don't want to
restore the raw bytes and neither do we want to stuff the bytes into a
utf-8 string. Emacs comes with its own encoding which was lost when
converting the code to Rust.
Perform this encoding step when dealing with multibyte output and set
the tests against outputs taken from running the upstream
implementation.
---
This is somewhat related to #499 as we can't return the bare decoded data nor can we let the Rust stdlib deal with it as a string
=> Fix base64 decoding into multibyte string

rust_src/src/editfns.rs, src/editfns.c
=> Port widen

rust_src/src/windows.rs, src/window.c
=> Port window-redisplay-end-trigger and set-window-redisplay-end-trigger

rust_src/src/coding.rs, src/coding.c, test/rust_src/src/coding-tests.el
=> Port coding-system-aliases and check-coding-system

Makefile.in, configure.ac, src/Makefile.in
This feature wasn't requested here. However, I find it very useful when developing, and I think it might be of use to other developers as well.
=> Make rustdoc

rust_src/src/base64.rs, rust_src/src/buffers.rs, rust_src/src/callproc.rs, rust_src/src/casefiddle.rs, rust_src/src/casetab.rs, rust_src/src/category.rs, rust_src/src/character.rs, rust_src/src/cmds.rs, rust_src/src/crypto/mod.rs, rust_src/src/data.rs, rust_src/src/decompress.rs, rust_src/src/editfns.rs, rust_src/src/fileio.rs, rust_src/src/keymap.rs, rust_src/src/lread.rs, rust_src/src/marker.rs, rust_src/src/minibuf.rs, rust_src/src/syntax.rs, rust_src/src/threads.rs, rust_src/src/windows.rs
This will make `ThreadState::current_buffer` method to return an `Option`
which is useful for null check.
=> Add ThreadState::current_buffer_unchecked method

rust_src/src/process.rs
=> respect our naming conventions

rust_src/src/eval.rs, rust_src/src/eval_macros.rs, rust_src/src/functions.rs, rust_src/src/lib.rs, rust_src/src/remacs_sys.rs, src/alloc.c, src/bytecode.c, src/charset.c, src/coding.c, src/eval.c, src/fontset.c, src/lisp.h, src/lread.c, src/nsfns.m, src/thread.c, src/w32select.c
=> Port signal

rust_src/src/buffers.rs, rust_src/src/indent.rs, rust_src/src/keymap.rs, src/indent.c
Not sure whether we should use EmacsUint or EmacsInt for a column number.
=> Port indent-to

rust_src/src/frames.rs, src/frame.c
=> Port frame-focus

rust_src/src/callproc.rs, rust_src/src/fileio.rs, rust_src/src/minibuf.rs, rust_src/src/multibyte.rs
=> Add is_empty predicate to strings

rust_src/src/callproc.rs, rust_src/src/chartable.rs, rust_src/src/editfns.rs, rust_src/src/fileio.rs, rust_src/src/minibuf.rs, rust_src/src/multibyte.rs
This closes #1230. (for real this time)
=> Add missing is_empty usages

rust_src/src/alloc.rs, src/alloc.c, src/lisp.h, test/rust_src/src/alloc-tests.el
=> Port record and make-record

rust_src/src/dired_unix.rs
Refactor while we are here.
Closes: #1267
=> Handle invalid byte sequence better.

rust_src/src/dispnew.rs, rust_src/src/frames.rs, rust_src/src/windows.rs
=> Update LispFrameOrSelected to LispFrameLiveOrSelected

rust_src/src/windows.rs
=> Fix translation of nils to windows.

rust_src/src/windows.rs, src/window.c
Simple enough port. Haven't been able to directly test due to #895.
Closes #1307
=> Port window-new-pixel.

default.nix
Probably overkill since most Nix devs will have it pre-installed, but
it doesn't hurt to be thorough.
=> Add autoconf and rustup to default.nix.

rust_src/src/eval.rs, src/eval.c
=> Port condition-case

docker/fedora/Dockerfile, docker/ubuntu/32bit/Dockerfile, docker/ubuntu/Dockerfile, docker/ubuntu/cosmic/Dockerfile
#1286 may have caused by incompatible version of Rust toolchain in Dockerfile.
=> Sync Rust version of Dockerized environment

rust_src/src/buffers.rs
(#1320, but with a slightly more strict `LispBufferOrName`)
This did require removing the derivation of `Eq` on the type, but no
changes outside the `buffers` module and trivial changes inside.
Maybe useful to the discussion in #1302 re: the benefits of wrapper
types vs. enums of various specificity.
=> Make the type guarantees in LispBufferOrName a little stronger.

src/lisp.h
=> Remove duplicate declaration

rust_src/src/fns.rs, rust_src/src/multibyte.rs, rust_src/src/vectors.rs, src/fns.c, test/rust_src/src/fns-tests.el, test/src/fns-tests.el
Closes #1247.
The code doing the actual reversing for each of the different types could be methods that this function calls. I'm not sure which is preferable.
=> Port reverse

rust_src/src/lread.rs
Includes @shaleh's temporary fix for #1333.
=> Temporary fix for #1333

src/nsterm.m, src/xdisp.c
Merge some commit's from GNU emacs master to fix #895 blank window issue. Make #1116 duplicated.
=> Merge emacs Mojave support

rust_src/src/lib.rs, rust_src/src/print.rs, src/print.c
I dont find print.rs, so make it.  ~~But, it cannot compile for some missing boilerplate codes ...~~
It will close #1079
=> port error-message-string

rust_src/src/windows.rs, src/window.c
My first attempt at coding in rust.
Not sure if test(s) can be written for this accessor fn..
Closes #1342
=> Port window-pixel-top

rust_src/src/windows.rs, src/window.c, test/rust_src/src/windows-tests.el
https://github.com/remacs/remacs/issues/1358
=> Port window-normal-size

rust_src/src/buffers.rs, src/buffer.c
=> Port buffer-enable-undo

rust_src/src/fileio.rs, src/fileio.c
=> Port make-temp-name

rust_src/src/frames.rs, src/xfaces.c
=> Port frame-face-alist

rust_src/src/windows.rs, src/window.c
Fixes: https://github.com/remacs/remacs/issues/1374
=> Port window-pixel-left

rust_src/src/windows.rs, src/window.c, test/rust_src/src/windows-tests.el
=> Port window-left-column

rust_src/src/callproc.rs, rust_src/src/dired_unix.rs, rust_src/src/editfns.rs, rust_src/src/eval.rs, rust_src/src/eval_macros.rs, rust_src/src/fileio.rs, rust_src/src/fns.rs, rust_src/src/lread.rs
Fix errors of [#1393](https://github.com/remacs/remacs/issues/1393).
=> Fix ARM aarch64 error

rust_src/src/fns.rs, src/fns.c, test/rust_src/src/fns-tests.el
=> Port vconcat

rust_src/src/buffers.rs
Also make a very minor improvement to `LispBufferRef::reset_local_variables`
=> Correct invocations of nreverse

rust_src/src/buffers.rs, rust_src/src/casetab.rs, rust_src/src/character.rs, rust_src/src/chartable.rs, rust_src/src/dired_unix.rs, rust_src/src/floatfns.rs, rust_src/src/fonts.rs, rust_src/src/frames.rs, rust_src/src/hashtable.rs, rust_src/src/keymap.rs, rust_src/src/lisp.rs, rust_src/src/lists.rs, rust_src/src/multibyte.rs, rust_src/src/obarray.rs, rust_src/src/symbols.rs
Suggested by the "nursery" Clippy lint missing_const_for_fn
=> Use const fn

rust_src/src/buffers.rs, rust_src/src/eval_macros.rs, rust_src/src/fns.rs
=> Implement lisp_concat macro

rust_src/src/process.rs, src/process.c
Port four small functions that wraps around [process_send_signal](https://github.com/Wilfred/remacs/blob/master/src/process.c#L6149) function.
This will close #1260
=> Port `process_send_signal' wrappers

rust_src/src/syntax.rs, src/syntax.c, test/rust_src/src/syntax-tests.el
Closes #1430 
I'm relatively new to Rust and this project, so let me know if I can improve anything.
=> Port scan-sexps

rust_src/src/fonts.rs, rust_src/src/frames.rs, src/font.c, src/font.h
Closes #1398.
Not sure how to add tests here, some pointers would be appreciated.
=> Port frame-font-cache.

rust_src/src/xdisp.rs, src/xdisp.c
Fixes #1448
I'm not entirely sure what to do about testing for this.
Note that this code is very similar to the "else" case of "force_mode_line_update" in buffers.rs, but I'm also not sure if/how that should be factored out.
=> Port set-buffer-redisplay

rust_src/src/coding.rs, src/coding.c, src/coding.h
Opening up PR to close issue #1481.
First time contributor, figured I would learn, and make changes as needed.
=> Port defun's decode-coding-string & encode-coding-string

rust_src/src/xsettings.rs, src/tempxsettings.h, src/xsettings.c
This builds on the groundwork laid down by the porting of the other xsettings defuns.
=> Port tool-bar-get-system-style

rust_src/src/keyboard.rs, src/keyboard.c, src/keyboard.h
=> Port read-key-sequence-vector

rust_src/src/alloc.rs, rust_src/src/marker.rs, src/alloc.c
This should hopefully close #1494.
I am quite new to rust so I am not too sure if the choices I made when it came to porting `XMARKER` are correct but hopefully this is enough to solve this issue. I also tried thinking of some tests but was not too sure as to how to test this exactly. Either way, I am looking forward to the code review. Thanks in advance!
=> Port make-marker [WIP?]

rust_src/src/lread.rs, rust_src/src/obarray.rs, rust_src/src/remacs_sys.rs, rust_src/src/symbols.rs, src/lread.c, test/rust_src/src/lread-tests.el
=> Port unintern

rust_src/src/textprop.rs, src/textprop.c
=> Port set-text-properties

rust_src/src/eval.rs, rust_src/src/lisp.rs, rust_src/src/symbols.rs, src/eval.c, src/lisp.h, test/rust_src/src/eval-tests.el
Closes https://github.com/remacs/remacs/issues/1475
=> Port defvar

rust_src/src/character.rs, src/character.c, test/rust_src/src/character-tests.el
=> Port char-resolve-modifiers

configure.ac
@shaleh 
Closes:
https://github.com/remacs/remacs/issues/1521
Partially fixes
https://github.com/remacs/remacs/issues/1513
=> revert remacs version to 26.2

rust_src/src/composite.rs, rust_src/src/fns.rs, rust_src/src/lib.rs, src/composite.c, src/fns.c, test/rust_src/src/composite-tests.el
=> Compose string internal

rust_src/src/buffers.rs, src/buffer.c, test/rust_src/src/buffers-tests.el
=> Port move overlay

rust_src/src/keymap.rs, src/keymap.c
=> port current-minor-mode-maps
