rust_src/src/cons.rs, rust_src/src/lisp.rs
While reading the rust side of the code base I saw a useful TODO I thought I would complete. Now XUNTAG will take a LispType instead of everywhere in the code base casting the enum value to an int.
=> Changing XUNTAG to accept a LispType instead of a c_int.

README.md
Also added a bit of instructions on creating a new issue when someone picks a task. The idea is we can use README to keep low hanging fruit available for people. Another option (maybe later, but much less visible)  would be to create issues for each task and tag them as unasigned, by complexity and such. 
By now I guess it's a good idea to have them (while they are few) discoverable on the readme.
=> Make tasks markdown checkable.

README.md
I often do my builds outside of the source tree.
I think this is the way to fix the note in the README.md so that someone who keeps their build directory elsewhere can still make forward progress.
(I am otherwise running into issues like #17 so I have not actually tested this change end-to-end, but it seems solid to me.)
=> make Makefile note robust when build dir != src dir.

README.md
I'm slow. It took me a couple tries to figure out that adding this line at the TOP of `src/Makefile` wasn't going to get me anywhere.
Maybe this will help the next poor sucker.
=> Indicate LIBS_SYSTEM setting should be modified not added

rust_src/src/lisp.rs
=> Use EmacsInt rather than assuming i64 is the same

.travis.yml, README.md, src/Makefile.in
LIBS_SYSTEM no longer has to be modified manually to build remacs.
README.md was updated to reflect that.
=> Fixed src/Makefile.in so that LIBS_SYSTEM is correct.

rust_src/Cargo.toml, rust_src/build.rs, rust_src/src/lisp.rs
Hi, according to lisp.h, this should be the correct definition of the emacs integer types. (Auto generated from build.rs)
With or without the patch, remacs still crashes during the bootstrapping phrase on my Windows machine. Will investigate more about this later.
=> Properly define the emacs integer types.

src/unexmacosx.c
Not really sure why these are missing in the remacs fork. Implies that the upstream repo doesn't build on MacOS either?
=> MacOS missing LC thread segments

.gitignore
Extremely minor, just fixes a missed rename.
=> Add src/remacs to .gitignore

rust_src/src/lisp.rs
There are a couple of errors when compiling for a 32 bits architecture.
This commit solves these errors.
=> Fix LispMisc type.

rust_src/src/atom.rs, rust_src/src/cons.rs, rust_src/src/lib.rs, src/data.c, src/lisp.h
Converts the `atom` function to Rust.
This required the use of `CONSP`, so I made it public in `cons.rs`, not sure if this is a reasonable thing to do.
Look forward to feedback
=> Ports the atom function to Rust

README.md
In the front-page README.md , there is a mistake in the tutorial example. C-function `Fnumberp` uses `NUMBERP` predicate, while the corresponding Rust implementation uses `SYMBOLP` for some reason.
=> missprint in the example code: NUMBERP->SYMBOLP

.travis.yml, Makefile.in, README.md, configure.ac, src/Makefile.in, test/automated/Makefile.in
Adds appropriate rules and dependencies to the existing autoconf/make
based build system. This includes the build process itself, ie make, make
clean and make check, obviating the need to manually edit the
makefiles to account for different build configurations.
The default optimisation level is --release, in line with the C
components. A configure option (--enable-rust-debug) has been added
that clears the arguments to cargo build, but leaves the C flags as is
(This matches the current "debug build" behaviour).
Arguments may be passed to cargo via the CARGO_FLAGS variable.
The RUSTFLAGS environment variable is also explicitly passed when
cargo build is invoked.
=> Integrate cargo with autoconf

rust_src/src/lib.rs, rust_src/src/marker.rs, src/marker.c
Hello @Wilfred,
here is implementation of `CHECK_MARKER()` from `src/marker.c`.
=> add rust implementation of CHECK_MARKER()

rust_src/build.rs, rust_src/src/lisp.rs
This make it possible to add our own methods.
I've added a few helper functions. Haven't added corresponding tests and change the subrs to actually use them though.
=> Use LispObject as a newtype of EmacsInt. 

README.md
@crlf0710 @dpzmick @jeandudey  (or anyone else who has an opinion!) does this seem like a good approach to you?
=> Document when functions should be marked unsafe

rust_src/src/lib.rs, rust_src/src/lisp.rs, rust_src/src/strings.rs, src/lisp.h
Additionally `STRINGP` moved to `lisp::deprecated` to be consistent with `FLOATP`, `NUMBERP` and etc..
=> Implementation of CHECK_STRING()

rust_src/src/lisp.rs
In other way we will get warning:
```
warning: function is never used: `XFLOAT_DATA`,
--> rust_src/src/lisp.rs:641:5
|
641 |     pub fn XFLOAT_DATA(f: LispObject) -> f64 {
|     ^
```
=> add dead_code attribute for XFLOAT_DATA for now

configure.ac
`dlopen(3)` is in libc on *BSD and libdl doesn't exist
=> do not link against libdl on *BSD

Makefile.in
This change ensures that the rust build is a dependency of all of
emacs' C code rather than just the src and lib-src directories
=> Improve makefile rust dependencies

.travis.yml
With this change travis successfully builds temacs
Now the failure is "emacs: Invalid function: cdr", which looks like an actual bug somewhere.
Question: Should mac and linux be given different configure args?
=> (Fix for os_x_build_on_travis branch) add --with-gnutls=no to travis.yml

src/Makefile.in
This ensures temacs is relinked if a new libremacs.a is present, ie if
rust-src has changed.
In my original patch I somehow left this out... Anyway, this makes sure
temacs is relinked if the cargo is rerun with different flags OR if the
libremacs.a archive file is updated.
Previously it only depended on cargo having been rerun with different
flags without changing the libremacs.a archive that temacs had been
built with. ie I handled the edge case and forgot about the rest... 🤦‍
=> Add temacs make rule dep on libremacs.a

rust_src/src/floatfns.rs, rust_src/src/lib.rs, rust_src/src/math.rs
Change the definition of Fabs to accurately reflect the behaviour of the
C version of the function. The previous version assumed that it's
argument was always a float, the C version works on both floats and ints
=> Fix Fabs to handle numberp

rust_src/build.rs, rust_src/src/lib.rs, rust_src/src/lisp.rs, rust_src/src/strings.rs, rust_src/src/symbols.rs
This does some refactoring and implement the non lsb tag case for lisp object. Resolves #74
=> Refactor and lsb

rust_src/src/lisp.rs
When debugging a lot of redundant calls are made, in somy way makes debugging more defficient.
This:
```
#0  0x0822ba17 in remacs::lisp::LispObject::get_type (self=...) at /home/jeandudey/rust-projects/remacs/rust_src/src/lisp.rs:174
#1  0x0822da3c in remacs::lisp::deprecated::XTYPE (a=...) at /home/jeandudey/rust-projects/remacs/rust_src/src/lisp.rs:714
#2  0x0822c35c in remacs::lisp::LispObject::is_string (self=...) at /home/jeandudey/rust-projects/remacs/rust_src/src/lisp.rs:430
#3  0x0822de9c in remacs::lisp::deprecated::STRINGP (x=...) at /home/jeandudey/rust-projects/remacs/rust_src/src/lisp.rs:798
#4  0x0822e2a9 in remacs::lisp::CHECK_STRING (x=...) at /home/jeandudey/rust-projects/remacs/rust_src/src/lisp.rs:874
```
Now becomest this in a `backtrace`:
```
#0  0x0822b9d8 in …
```
=> Make CHECK_STRING use LispObject::is_string.

.travis.yml, test/lisp/progmodes/elisp-mode-tests.el, test/lisp/vc/vc-bzr-tests.el, test/lisp/vc/vc-tests.el
Helps with #99 by ensuring we don't break any additional tests.
=> Skip the currently failing tests, but require the rest to pass on travis

Makefile.in, src/Makefile.in
* Moved rust compilation inside the src-Makefile
* Added a target to build the build the remacs archive. This target
depends on all rust src files
All examples assume a previously completed run of `make` or `make src` and abbreviates some output with `[...]`
```shell
$ touch rust_src/src/lisp.rs
$ make src
make -C lib all
[...]
make[2]: 'libXMenu11.a' is up to date.
make[2]: Leaving directory '/home/jonas/workspace/remacs/oldXMenu'
RUSTFLAGS= \
cargo build --release --manifest-path ../rust_src/Cargo.toml
Compiling remacs v0.1.0 (file:///home/jonas/workspace/remacs/src/../rust_src)
note: link against the following native artifacts when linking against this static library
note: the order and any duplication can be significant on some platforms, and so may need to be preserved
note: library: …
```
=> Recompile with cargo and rebuild temacs when the Rust source changes

configure.ac, rust_src/src/lisp.rs, src/.gdbinit, src/alloc.c, src/lisp.h
Consistency between Rust and Remacs C code.
- `configure.ac`: Remove `--enable-check-lisp-object-type`.
- `rust_src/src/lisp.rs`: Remove comment about `CHECK_LISP_OBJECT_TYPE`.
- `.gdbinit`: GDB script was updated to treat `Lisp_Object` as a normal integer and not a `struct`.
- `lisp.h`: All preprocessor relating to `CHECK_LISP_OBJECT_TYPE` was removed leaving default code in place.
=> Remove --enable-check-lisp-object-type configure flag.

test/lisp/progmodes/elisp-mode-tests.el
This is intended to test the robustness of case-insensitive file
systems. However, on case-sensitive file systems, this doesn't
work. Travis CI is using /home/travis/build/Wilfred/remacs but Emacs
would look for /home/travis/build/wilfred/remacs and fail.
This enables the xref tests to run on travis. See #99.
This issue has been filed upstream:
https://debbugs.gnu.org/cgi/bugreport.cgi?bug=25534
=> Don't downcase the emacs test directory

rust_src/Cargo.lock, rust_src/Cargo.toml, rust_src/alloc_unexecmacosx/Cargo.toml, rust_src/alloc_unexecmacosx/src/lib.rs, rust_src/src/lib.rs
Use custom allocator on Mac OS X to uphold the rule that all calls to malloc/realloc/free go through their `unexec_`-prefixed variants on OS X.
The changes are hopefully properly conditionalized so that they do not affect non Mac OS X targets. It would be good for someone with a Linux box to verify this claim.
----
We will probably need to go through a similar process for targets that do not have native support for `unexec`; you can get a feel for the set of targets this means by doing `% ls src/unex*.c`:
```
src/unexaix.c		src/unexcw.c		src/unexhp9k800.c	src/unexsol.c
src/unexcoff.c		src/unexelf.c		src/unexmacosx.c	        src/unexw32.c
```
(Of course we do not actually *care* about all of those targets...)
----
Also, one more thing: I am not sure whether this is a bug in my PR, or a …
=> Use custom allocator on Mac OS X

src/Makefile.in
Incorporate OS X allocator into Makefile deps.
Fix #120
=> Incorporate OS X allocator into Makefile deps.

rust_src/remacs-sys/lib.rs, rust_src/src/lib.rs, rust_src/src/lisp.rs
`LispSubr` is now `Lisp_Subr` in `remacs-sys`.
=> Move LispSubr to remacs-sys

rust_src/src/lisp.rs
I have a build error
> Compiling libc v0.2.17
>    Compiling rustc-serialize v0.3.22
>    Compiling lazy_static v0.2.2
>    Compiling remacs-sys v0.1.0 (file:///******/remacs/rust_src/remacs-sys)
>    Compiling remacs v0.1.0 (file:///******/remacs/src/../rust_src)
> error[E0412]: type name `EmacsInt` is undefined or not in scope
>    --> ../rust_src/src/lisp.rs:620:34
>     |
> 620 |     pub fn XLI(o: LispObject) -> EmacsInt {
>     |                                  ^^^^^^^^ undefined or not in scope
>     |
>     = help: you can import it into scope: `use remacs_sys::EmacsInt;`.
> 
> error[E0412]: type name `EmacsInt` is undefined or not in scope
>    --> ../rust_src/src/lisp.rs:627:19
>     |
> 627 |     pub fn XIL(i: EmacsInt) -> LispObject {
>     |                   ^^^^^^^^ …
=> Fix rust build

test/lisp/emacs-lisp/eieio-tests/eieio-tests.el
See #159.
This caused legitimate PRs #153 and #158 to fail.
=> Skip EIEIO test that fails non-deterministically on Travis

rust_src/src/strings.rs
The 32 bit compilation was broken because of an invalid cast.
=> Cast to EmacsInt instead of i64 on strings.rs

rust_src/src/lib.rs
This function was used for debugging but now it isn't needed anymore.
=> Remove rust_print_lisp_object function

rust_src/alloc_unexecmacosx/src/lib.rs
A change in Rust internals caused us errors with the linker,
this commit solves this.
=> Implement `__rust_allocate_zeroed` on alloc_unexecmacosx

rust_src/src/character.rs, rust_src/src/lib.rs, src/character.c
This is my first experience on rust. I started porting a single function from character.c which also needed to port a macro from character.h which I did not delete after porting.
This compiles and the function works
But I noticed documentation is not working, neither in this function nor in other ported functions. like `max-char` or the one of the readme page `numberp`
Looking forward to listen from your reviews
=> Porting characterp

rust_src/remacs-sys/lib.rs, rust_src/src/floatfns.rs, rust_src/src/lisp.rs, rust_src/src/lists.rs, rust_src/src/math.rs, rust_src/src/numbers.rs, rust_src/src/strings.rs
In a effort to refactor lisp.rs i moved some extern functions and
statics to remacs-sys.
=> Move `extern "C"` block to remacs-sys

configure.ac, lib-src/Makefile.in
Fix for https://github.com/Wilfred/remacs/issues/187, which will cause users on certain OSX versions to be unable to build remacs. 
I've also included a separate commit to fix another issue I noticed while fixing this one; running `make clean` in lib-src will not run cargo clean for remacs-lib.
=> Fix for issue #187. 

rust_src/remacs-lib/lib.rs, rust_src/remacs-lib/math.rs, src/data.c, src/remacs-lib.h
This PR will allow us to delete:
```
lib/count-one-bits.c
lib/count-one-bits.h
lib/count-trailing-zeros.c
lib/count-trailing-zeros.h
```
By replacing the functionality provided in these files by function provided by the Rust standard library. 
I will submit the deletion of those files as a separate PR, as it looks like people (including myself!) have been removing files from lib/ without running gnulib-tool to re-generate the make files. Running gnulib-tool now with the proper generation command leads to some slightly incorrect makefiles, and that will need to be corrected.
=> Converting 'count-trailing-zeros' and 'count_one_bits' to Rust

rust_src/remacs-lib/lib.rs, rust_src/remacs-lib/math.rs, src/data.c, src/lisp.h, src/remacs-lib.h
This PR allows us to delete several legacy codepaths in data.c for determining the number of trailing 0 bits in a bits_word, and the number of total one bits in a bits_word. These functions can now be easily farmed out to the standard rust implementation.
=> Updating 'bits_word' to always be a typedef for size_t. 

.travis.yml
Currently, the build fails every time a new version of rustfmt comes out. This is surprising for PR authors, who expect the build to be green other than any changes they might make.
Pin to the latest version of rustfmt as this time of writing.
This will fail because our source code is currently formatted for 0.8.x and rustfmt 0.9.0 is out. I will fix this in this branch, unless #203 is merged first.
=> Explicitly pin a rustfmt version

rust_src/remacs-lib/files.rs, rust_src/remacs-lib/lib.rs, rust_src/remacs-lib/math.rs, rust_src/src/crypto/mod.rs, rust_src/src/lisp.rs, rust_src/src/marker.rs, rust_src/src/strings.rs
Also switch to always using libc types without prefix.
=> Cleanup: use "extern crate" only in crate root

rust_src/src/lib.rs, rust_src/src/multibyte.rs, rust_src/src/strings.rs, src/fns.c
This PR converts 'string-to-unibyte' from C to Rust. I've also added const ptr getter methods to LispStringRef, since it seemed like we don't always want to take ownership of the string if we only want it as a const pointer.
=> Converting 'string-to-unibyte' from C to Rust.

rust_src/remacs-sys/lib.rs, rust_src/src/character.rs, rust_src/src/lib.rs, rust_src/src/lisp.rs, rust_src/src/vectors.rs, src/data.c
I've recreated this PR with a fresh branch from the master. Everything should be implemented and good to go.
Let me know if there is anything I've missed or can clean up. I'm still very new to Rust and Remacs
=> moved vector functions into rust

.travis.sh, README.md, rust_src/remacs-macros/function.rs, rust_src/remacs-macros/lib.rs, rust_src/remacs-macros/lisp_attr.rs
I updated the travis script to format remacs-macros.
Cargo fmt would hang when run as
```bash
cargo fmt -- --write-mode=diff
```
but by specifying the base file to format seems to prevent it from hanging.
```bash
cargo fmt -- --write-mode=diff lib.rs
```
example:
```bash
remacs/rust_src/remacs-macros
▶ cargo fmt -- -v --write-mode=diff lib.rs
Formatting /Users/mark/prog/remacs/rust_src/remacs-macros/function.rs
Formatting /Users/mark/prog/remacs/rust_src/remacs-macros/lib.rs
Formatting /Users/mark/prog/remacs/rust_src/remacs-macros/lisp_attr.rs
```
So the question is, is this an acceptable fix?
I also ran cargo fmt over the remacs-macros source and updated the readme to reflect the additions of the format checker.
=> travis formatting for remacs-macros

rust_src/remacs-sys/lib.rs, rust_src/src/lib.rs, rust_src/src/lisp.rs, rust_src/src/multibyte.rs, rust_src/src/strings.rs, rust_src/src/symbols.rs, src/fns.c
This is a WIP PR for porting string-lessp to Rust. As part of this work, it seemed useful to add an iterator for a LispStringRef, in order to replace the macro FETCH_STRING_CHAR_ADVANCE
Work left to do:
=> Port 'string-lessp' to Rust

rust_src/Cargo.lock, rust_src/alloc_unexecmacosx/Cargo.toml, rust_src/alloc_unexecmacosx/src/lib.rs, rust_src/src/lib.rs
Updating the custom MacOSX allocator to use the new Global Allocator API, that was recently merged as part of 1.20 nightly. This API is considered unstable, but we will attempt to keep up with a moving target.
Information on this API was gathered from https://github.com/rust-lang/rfcs/pull/1974#issuecomment-306249616 and https://github.com/rust-lang/rust/issues/32838
Work to still be done:
=> Fix OSX build on 1.20 nightly. 

rust_src/src/multibyte.rs
Fixing issue where running '(string-as-multibyte "\255")' would cause remacs to panic. This was caused by some faulty iteration logic in multibyte::str_as_multibyte. This should fix https://github.com/Wilfred/remacs/issues/222
Looking over the C code, I believe the two additions in this diff are needed to fix this problem. In an older version of character.c, before we ported some of the multibyte functions, we had 
```
ptrdiff_t
str_as_multibyte (unsigned char *str, ptrdiff_t len, ptrdiff_t nbytes,
ptrdiff_t *nchars)
{
unsigned char *p = str, *endp = str + nbytes;
unsigned char *to;
ptrdiff_t chars = 0;
int n;
while (p < endp
&& ! CHAR_BYTE8_HEAD_P (*p)
&& (n = MULTIBYTE_LENGTH (p, endp)) > 0)
p += n, chars++;
if (nchars)
*nchars = chars;
if (p == endp)
return nbytes;
to = p;
nbytes = …
```
=> Fixing (man "ls") panic, due to str_as_multibyte logic 

rust_src/src/lib.rs, rust_src/src/symbols.rs, src/data.c
Porting 'symbol-name', 'fboundp', 'symbol-function', and 'symbol-plist' to Rust.
=> Port some basic symbol related functions to Rust

rust_src/remacs-sys/lib.rs, rust_src/src/buffers.rs, rust_src/src/floatfns.rs, rust_src/src/lisp.rs, rust_src/src/lists.rs, rust_src/src/math.rs, rust_src/src/symbols.rs, src/data.c
Also port float_arith_driver to avoid awkward recasting as raw lisp objects.
=> Refactor math functions a bit with more Rusty matching and less checking

autogen.sh
We have had a number of new contributors not realize that remacs requires nightly rust, and this has caused problems. This should make the build fail fast if nightly is not installed.
=> Adding nightly validation to autogen.sh. 

README.md
This was not obvious before. Related: #241, #243.
=> Document that we require nightly on all platforms

Makefile.in, README.md
I removed the `gcc -E` advice because it's tricky to get right
(see #229) and not really necessary anymore.
=> Update README; add format target to Makefile.

test/lisp/emacs-lisp/eieio-tests/eieio-test-methodinvoke.el
Note this fails on upstream GNU Emacs on Hydra (their CI tool) too.
See #159.
=> Skip EIEIO test that fails on Travis

rust_src/remacs-sys/lib.rs, rust_src/src/lib.rs, rust_src/src/lisp.rs, rust_src/src/vectors.rs, rust_src/src/windows.rs, src/window.c
This PR ports window-live-p to Rust. Because I followed the approach used by buffer-live-p, it includes a struct Lisp_Window in remacs-sys/lib.rs. If this isn't the right approach let me know, and I'll try again!
It seems to work as expected in ielm.
Closes Issue #232.
=> Port window-live-p to Rust

rust_src/src/lib.rs, rust_src/src/process.rs, src/process.c
Porting `processp` to rust per [#229](https://github.com/Wilfred/remacs/issues/229).
Not much more to it.  Went smooth once I found `is_process` :smile:. Great community support, too, thanks!
=> Port processp

rust_src/remacs-sys/lib.rs, rust_src/src/symbols.rs
It's a common pattern in the C codebase to call `intern("some static c string")`. I thought that it would be nice to have a similar API available in Rust. Unfortunately, there's no way of doing this with the `std::cstring` interface that avoids heap-allocating and unnecessary copies. I've written a macro that avoids this by concatenating a null byte to the end of a string at compile time, and casting to a `*const c_char`. This allows us to write 
```rust
let symbol = unsafe { intern_static!("my-symbol-1") };
```
This macro is, and always will be, unsafe. If you pass it a string with internal NULL bytes, e.g. `intern("my-\0dangerous-\0string")`, then C will not correctly deduce the length of the string, and we'll leak memory. However, for symbols defined at compile time and clearly audited …
=> Adds intern and an intern_static! macro

src/process.c
A form-feed was removed mistakenly.  This adds it back in.
=> Add removed form-feed back in

rust_src/remacs-sys/lib.rs, rust_src/src/base64.rs, rust_src/src/character.rs, rust_src/src/eval.rs, rust_src/src/floatfns.rs, rust_src/src/lib.rs, rust_src/src/lisp.rs, rust_src/src/lists.rs, rust_src/src/marker.rs, rust_src/src/math.rs, rust_src/src/multibyte.rs, rust_src/src/strings.rs, rust_src/src/vectors.rs
Vararg constructs in C should be replaced by macros, such as `error(fmt, ...)` which now uses Rust's formatting machinery.
Multitudes of functions with the same purpose like `xsignalN` and `callN` can also be replaced by macros on the Rust side.
=> Add some macros for convenience and safety

rust_src/remacs-sys/lib.rs, rust_src/src/fonts.rs, rust_src/src/lib.rs, rust_src/src/lisp.rs, src/font.c
This is my first pass at porting `fontp` to Rust, and should be considered a work in progress. I have a few questions:
1) ~~Should I change the naming convention for the `font_property_index` enum?~~
2) ~~Is there a convention for calling `intern` from Rust code?~~ See #255.
3) ~~Can or should I add `is_font_spec()` (etc) methods to `LispObject` in `lisp.rs`, so that the checking can be moved out of `fontp` and into those methods?~~
This should close #233.
=> Port fontp to Rust

rust_src/src/fonts.rs
Looks like we merged two PRs around the same time, and missed a call to wrong_type_argument. This PR corrects that.
I had to add an #[allow(unused_unsafe)] to from_symbol_or_error, since this call to wrong_type_argument doesn't have an unsafe predicate. We could try and work around this with macro magic, or traits, but I figured this was the easiest way for now since 99% of the uses cases need that unsafe block.
=> Fix for build being broken due to bad call to wrong_type_argument. 

rust_src/src/buffers.rs, rust_src/src/lib.rs, rust_src/src/threads.rs
Defining `current-buffer` in Rust requires us to have the `thread_state` type defined.
This definitely isn't finished yet, but any feedback welcome :)
=> Define a thread_state type and the current-buffer function

rust_src/remacs-sys/lib.rs, rust_src/src/category.rs, rust_src/src/fonts.rs, rust_src/src/lib.rs, rust_src/src/lisp.rs, rust_src/src/obarray.rs, rust_src/src/symbols.rs, src/category.c, src/lisp.h, src/lread.c
This PR ports a chunk of the obarray-related code from `lread.c` to Rust, including the lisp functions `intern` and `intern-soft`. I had to add some extern functions to the C code in order to get access to some global state.
=> Add LispObarrayRef and port intern functions to Rust

rust_src/src/buffers.rs, rust_src/src/editfns.rs, rust_src/src/lib.rs, src/editfns.c
I'm still struggling with git :)
=> port some functions

rust_src/src/editfns.rs, rust_src/src/lib.rs, src/editfns.c
This is my first contribution.  
Porting bobp to rust
=> Port bobp to rust

rust_src/src/crypto/mod.rs, rust_src/src/eval.rs, rust_src/src/fonts.rs
libc's underlying type differs between x86-64 (i8) and arm (u8).
=> fix 32-bit arm compilation

rust_src/src/buffers.rs, rust_src/src/lib.rs, rust_src/src/lisp.rs, src/buffer.c
I think the code as it is now should be functionally equal to the C code. It might be a little less efficient as we are setting the `*b` and `*e` on every validation regardless if something changed or not.
=> Translate validate_region

rust_src/src/lib.rs
This changed in https://github.com/rust-lang/rust/pull/42588.
=> Fix new warning on latest Rust nightly

rust_src/src/buffers.rs, rust_src/src/editfns.rs, rust_src/src/lib.rs, src/editfns.c
With the PR as it is, I get `^^^^^^^^^^ expected u8, found char`, which makes sense because I'm comparing the address offset address with the char '\n' itself.   
I couldn't find the function that would get the char at a given addr (something with a signature like: buffer.char_at_addr(addr)).    Do we have such function? 
Also, is that use of unsafe, safe? :) or at least, sensible?
=> Port bolp and eolp to rust

rust_src/remacs-sys/README.md
Here is a first draft which describe the relationship between `remacs-sys` and `remacs`. It is a `README` file, inspired from  `remacs-macros` and `remacs-lib`.
Please let me know what you think. I have the following points in mind:
1. Note that English is not my first language, hence typos or grammar can be wrong. 
2. I aimed a detailed and beginner friendly documentation. Maybe a more tersed documentation would be better?
3. Should I talk about other topic in the `README`?
[ticket: #157]
=> Document the relationship between remacs-sys and remacs

rust_src/Cargo.lock, rust_src/Cargo.toml, rust_src/src/functions.rs, rust_src/src/lib.rs, rust_src/src/lisp.rs
Adding ability to mock extern "C" functions  defined by the emacs C layer. This is done via a mocking library using proc macros. Adding a basic test as an example.
This is the solution that was discussed in https://github.com/Wilfred/remacs/issues/299 It is using a library that I maintain, which can be found here: https://github.com/DavidDeSimone/mock_derive
=> Adding ability to mock extern "C" functions 

rust_src/src/lib.rs, rust_src/src/windows.rs, src/window.c
=> implemented window-start

rust_src/src/buffers.rs, rust_src/src/cmds.rs, rust_src/src/lib.rs, src/cmds.c
=> port forward point

configure.ac, lib-src/Makefile.in, rust_src/remacs-lib/Cargo.toml, rust_src/remacs-lib/lib.rs, src/Makefile.in
Fixes https://github.com/Wilfred/remacs/issues/330. The problem here is that cargo will create static libs named "x_lib.lib" instead of the expected "libx_lib.a" on gnu/linux or osx.
NOTE: While temacs will be able to build with this patch, we will not finish building our final emacs executable. This is further discussed here: https://github.com/Wilfred/remacs/issues/337
=> Fixing remacs build on mingw.

rust_src/remacs-sys/lib.rs, rust_src/src/lib.rs, rust_src/src/process.rs, src/process.c
=> implemented process-name

.travis-format.sh, .travis.yml
This should help new contributors, who are often caught out by Travis
requiring rustfmt. Using separate stages with clear names should be
easier than trying to read the (somewhat noisy) logs.
Whilst build stages are a beta feature:
https://docs.travis-ci.com/user/build-stages/ they have been available
for several months, since May 2017:
https://blog.travis-ci.com/2017-05-11-introducing-build-stages
=> Use Travis build stages

rust_src/src/lib.rs, rust_src/src/windows.rs, src/window.c
=> Ported window-margins

README.md
I presume that the `\` char removed by this commit is not meant to be there. Sorry for the noise if it is.
=> Fix unnecessary '\' escaping in README.md

rust_src/remacs-sys/lib.rs, rust_src/src/hashtable.rs, rust_src/src/lib.rs, rust_src/src/lisp.rs, rust_src/src/vectors.rs, src/fns.c
One common pattern in C to loop over key/value pairs in a Lisp_Hash_Table is:
``` c
for (i = 0; i < HASH_TABLE_SIZE (h); ++i) 
{
if (NILP (HASH_HASH (h, i))
continue;
key = HASH_KEY (h, i);
value = HASH_VALUE (h, i);
// ...
}
```
I believe it would be more idomatic Rust to use an iterator, so I wrote one. There is a base iterator, that iterates over the indices of `key_and_value`. This iterator is used to implement a key and value iterator. Usage looks like
``` rust
for (key, value) in hash_table.iter() {
// ...
}
```
=> Porting puthash/maphash/hash_table_count

rust_src/src/lib.rs, rust_src/src/process.rs, src/process.c
I'm renewing my interest in practicing rust, I'm an early beginner in it.
I followed the porting of process-name, this compiled and seems to work.
Is there a way to write tests for this? I very naively used `(run-python)` to have a process launched and then `(process-buffer (get-buffer-process "*Python*"))` to use this function. 
A side question. Why are Pull Requests at this beginner level not squashed when merged? It makes it quite complicated when reviewing the history see various commits that where the trials of the same patch. Having some cleanup of the commit history seems to help in the long run. Squashing on merge is very simple on github.
=> Close #375 Port process-buffer to rust

rust_src/remacs-macros/lib.rs, rust_src/remacs-macros/lisp_attr.rs
An example would be 
``` rust
#[lisp_fn(intspec="r")]
fn blah....
```
To define the function as interactive, acting on the current region.
=> Updating the 'lisp_fn' macro to support interactive functions.

rust_src/src/lib.rs, rust_src/src/windows.rs, src/window.c
Add a `frame` method to `LispWindowRef` to get the window's frame.
=> Port window-frame

.travis.yml, README.md, rust_src/src/lisp.rs
Rust 1.22 aka 2017-10-22
rustfmt 0.2.9
We can bump back to current when the upstream churn settles.
=> Lock versions

rust_src/remacs-sys/lib.rs, rust_src/src/lib.rs, rust_src/src/windows.rs, src/frame.c, src/frame.h, src/window.c
Document why `Lisp_Frame` cannot be filled in easily.
Add the needed access functions in src/frame.c.
Create `frame()`, `total_width()`, and `total_height()` methods
on `LispWindowRef`.
Closes #355
=> Port total-window-width and total-window-height

rust_src/src/base64.rs, rust_src/src/data.rs, rust_src/src/hashtable.rs
Trivial docstring change to add backticks for identifiers and code sections
=> Apply clippy for doc identifier markdown

rust_src/src/editfns.rs
@DavidDeSimone your code from #386 doesn't work correctly. It seems `goto-char` is the only interactive function we have ported so far.
=> add intspec to goto-char

rust_src/remacs-sys/lib.rs, rust_src/src/process.rs, src/process.c, src/process.h
I gave a try to this, but I got stuck.
I added the `pid` attribute to the `Lisp_Process` structure, but where do I assign the value for it when the struct is instantiated?
I was also wondering about the `make_fixnum_or_float`, does it make sense to use it here in remacs? When would the process_id overflow to be transformed as an int. Maybe is there for some legacy reasons but the type `libc::pid_t=i32` that should be enough for all process_id?
=> Port process-id to Rust Closes #431

rust_src/rustfmt.helper.sh
This works around the issue on Linux where rustfmt-nightly cannot find the
Rust compiler's shared libraries.
=> Add rustfmt helper example.

rust_src/remacs-sys/build.rs, rust_src/remacs-sys/lib.rs, rust_src/src/process.rs, src/process.c, src/process.h
#419 
The type of kill_without_query is actually a bool_bf rather than a bool.  See conf_post.h
```
/* The type of bool bitfields.  Needed to compile Objective-C with
standard GCC.  It was also needed to port to pre-C99 compilers,
although we don't care about that any more.  */
#if NS_IMPL_GNUSTEP
typedef unsigned int bool_bf;
#else
typedef bool bool_bf;
#endif
```
Both my c-fu and rust-fu are insufficient to work out what to do about that.  Everything compiles but I get a segfault - I think whenever remacs attempts to access kill_without_query.
The switch from 'query-on-exit' at the lisp level to the boolean opposite 'kill-without-query' at the c level was annoying, but I guessed this is not the time or place to try and fix that.
I originally went looking for an `as_bool_or_error`, just …
=> port process_query_on_exit_flag and set_process_query_on_exit_flag

.appveyor.bat
https://ci.appveyor.com/project/Wilfred/remacs/build/1.0.144 seems to have stalled. Remote-desktoping into the build doesn't reveal any obvious signs. I believe it may be related to our parallelism, so I would like to cut us down to 1 core down from 3 to see if that helps.
=> Reducing appveyor make to 1 core in an effort to fix stalling builds

rust_src/src/dispnew.rs
I will look into #494 to avoid this type of problems in the future.
=> Add missing cast to i64

rust_src/src/data.rs
Using `LispObject` directly caused a segmentation fault on 32 bit
systems.
=> Use Lisp_Object instead of LispObject in indirect_function

rust_src/remacs-sys/lib.rs, rust_src/src/cmds.rs, rust_src/src/keymap.rs, rust_src/src/lib.rs, src/cmds.c, src/emacs.c
Add mechanism to set initial keybindings in Rust.
=> Port forward-char and backward-char

rust_src/src/minibuf.rs
The C source makes this a EMACS_INT and uses it directly as a number.
=> minibuf_level is a number not an object

rust_src/src/base64.rs
=> Use LF not CRLF when calling base64::encode_config

src/fns.c
I introduced this to fix a local error under some circumstance, but now it is duplicate.
=> Remove duplicate hash_clear() prototype.

rust_src/build.rs, rust_src/src/base64.rs, rust_src/src/buffers.rs, rust_src/src/category.rs, rust_src/src/character.rs, rust_src/src/chartable.rs, rust_src/src/crypto/mod.rs, rust_src/src/dispnew.rs, rust_src/src/editfns.rs, rust_src/src/floatfns.rs, rust_src/src/fns.rs, rust_src/src/hashtable.rs, rust_src/src/interactive.rs, rust_src/src/keymap.rs, rust_src/src/lists.rs, rust_src/src/marker.rs, rust_src/src/math.rs, rust_src/src/minibuf.rs, rust_src/src/numbers.rs, rust_src/src/obarray.rs, rust_src/src/objects.rs, rust_src/src/process.rs, rust_src/src/strings.rs, rust_src/src/symbols.rs, rust_src/src/vectors.rs, rust_src/src/windows.rs
Enforce this by in the build process.
Also, remove export files if there are no longer exported functions.
This prevents odd compilation issues when the sole exported function
in a module has its #[lisp_fn] macro commented out to help debug a
compilation error.
=> lisp_fn exported functions should be public within rust too.

.travis.yml
Remove our own attempt to install it which is causes build failures.
=> Latest Travis includes GNUTLS for OSX.

rust_src/Cargo.lock, rust_src/Cargo.toml, rust_src/src/base64.rs, src/fns.c
I would like to move decode to no allocation as well. However, the
only mechanism upstream uses a Vector which cannot be traded with C.
Once I get information about decode we can merge this.
=> Refresh base64 support

rust_src/src/buffers.rs, rust_src/src/data.rs, rust_src/src/ffi.rs, rust_src/src/keyboard.rs, rust_src/src/lib.rs, rust_src/src/lisp.rs, rust_src/src/lists.rs, rust_src/src/math.rs, rust_src/src/multibyte.rs, rust_src/src/vectors.rs, rust_src/src/windows.rs
It looks like we were either a) using #[no_mangle] without an extern "C", and b) using LispObjects in extern "C" functions, which has caused issues with ffi in the past (see https://github.com/Wilfred/remacs/pull/496).
Once I cleaned up our FFI, several new unused_code warnings came up. I added some allow(dead_code) statements, since we will most likely want these functions available in the future.
=> Fixing areas of the codebase where we were mismanaging FFI with Rust functions.

rust_src/build.rs, rust_src/src/buffers.rs, rust_src/src/data.rs, rust_src/src/ffi.rs, rust_src/src/keyboard.rs, rust_src/src/lib.rs, rust_src/src/lisp.rs, rust_src/src/lists.rs, rust_src/src/math.rs, rust_src/src/multibyte.rs, rust_src/src/vectors.rs, rust_src/src/windows.rs
Catch no_mangle without extern "C"
Catch LispObject arguments or returns for extern "C" functions
Part of #496 and PR #528
=> Add explicit linting code.

etc/remacs.service
remacs service now launches `remacs` instead of `emacs`.
=> Fix systemd user remacs service

rust_src/remacs-sys/build.rs
EMACS_BOOL_SIZE is not used anywhere, nor is it documented so it can
be removed
=> Simplify BoolBF type generator

rust_src/remacs-sys/lib.rs, rust_src/src/lisp.rs, rust_src/src/multibyte.rs, rust_src/src/strings.rs, src/fns.c
Includes a minor refactor of the as_string_* APIs, to make them a little more DRY. Adds new functions to LispStringRef, to replace some C macros used in clear_string.
=> Porting clear_string to Rust.

rust_src/src/lisp.rs
Should use EmacsInt not i64.
Closes #497
=> Incorrect casts for 32 bits

rust_src/admin/pre-commit
The `set -e` line caused the script to exit prematurely. This
prevented the script from emitting a pretty error.
=> Precommit should not bail when called programs error.

rust_src/src/threads.rs, src/thread.c
Address #422.
#325 is an older PR but I used it as a guide on how the thread functions are being ported. PR could probably use some work before getting merged so I've put what I have so far (simple stuff right now) for critique. Specifically it would be nice to avoid the mucking around with `std::ptr::null_mut`, I saw that the field I'm using it for is marked TODO in the thread struct anyway, not sure what future plans are on that.
And are the boolean conversions in match necessary for returning Lisp objects? I was surprised at the lack of a `From` impl for `bool` to `LispObject`.
=> Port thread-alive-p.

rust_src/remacs-sys/lib.rs, rust_src/src/buffers.rs, src/buffer.c
This seems to work, but calls LispObject::from on Lisp_Object values,
which is incorrect. When corrected to LispObject::from_raw, half a
dozen tests faile.
This reverts commit 9e9ece6902ebba7676669f5400ccd2c9ba159adb.
=> Revert "port barf-if-buffer-read-only"

rust_src/src/data.rs, rust_src/src/floatfns.rs, rust_src/src/lisp.rs
This depends on #539, which introduces a call to build_string and all the attendant hoops, prompting me to write this.
=> implements LispObj::from(&str)

src/macfont.m
Took this from here: https://lists.gnu.org/archive/html/emacs-devel/2016-06/msg00630.html
I don't know if Remacs wants to get into political territory (stand up for emojis ✊!) or not, but this change made my day =)
Please feel free to completely ignore this, and many thanks for Remacs!
Revert "Disable multicolor fonts on OS X since they are not supported on free systems"
This reverts commit 9344612d3cd164317170b6189ec43175757e4231.
=> Bring back emoji 👿

rust_src/Cargo.lock, rust_src/remacs-macros/Cargo.toml, rust_src/remacs-macros/lib.rs
otherwise, even a properly-escape quote or baskslash in the macro
invocation will cause us to emmit code that can't compile.
=> escape quotes and backslashes when we use a byte literal in the lisp_fn macro

rust_src/src/windows.rs, src/window.c, test/rust_src/src/windows-tests.el
Tested it with:
```
(window-display-table)
;; https://www.gnu.org/software/emacs/manual/html_node/elisp/Display-Tables.html
(setq disptab (make-display-table))
(dotimes (i 32)
(or (= i ?\t)
(= i ?\n)
(aset disptab i
(vector (make-glyph-code ?^ 'escape-glyph)
(make-glyph-code (+ i 64) 'escape-glyph)))))
(aset disptab 127
(vector (make-glyph-code ?^ 'escape-glyph)
(make-glyph-code ?? 'escape-glyph)))
(set-window-display-table (get-buffer-window) disptab)
(window-display-table)
```
This is my very first PR. So there's a good chance that I might have missed something.
But I  successfully built Remacs, and the above snippet works the same on regular Emacs.
Should I also start porting `set-window-display-table` ?
=> Port window-display-table (#571)

rust_src/remacs-sys/lib.rs, rust_src/src/frames.rs, src/frame.c, src/frame.h
Ported over frame-pointer-visible-p as per issue #572.
=> Port frame-pointer-visible-p from frame.c

INSTALL
@shaleh I found only refs to this in the INSTALL file so no changes in readme
=> issue #629 followup: instruction on cargo build and install usage

rust_src/src/character.rs, rust_src/src/editfns.rs, src/editfns.c
As referenced in issue #407. I've never had to do pointer arithmetic in Rust before, so there might be a cleaner way to implement the `DEC_POS` macro.
=> Port the preceding-char function

rust_src/remacs-sys/build.rs, rust_src/remacs-sys/lib.rs, rust_src/src/eval.rs, rust_src/src/fns.rs, src/eval.c, src/fns.c
Also port un_autoload.
Make Qnil and friends const instead of static which allows them in
turn to be used in other statics.
=> Port require

rust_src/src/keymap.rs, src/keymap.c, test/rust_src/src/keymaps-test.el
Successfully ported `keymap-prompt` from `keymap.c` with tests. Closes #649.
- The code works but I am unsure if the style I used is correct. 
- I learned that returning inside a for loop doesn't work so I had to pass it to the `result` variable so it can be returned by the function.
- I've also separated the Ffoo imports from the other function imports.
Thanks!
=> Ported keymap-prompt with Tests.

src/keymap.h
Quick fix for the compilation warnings shown below:
```c
keymap.h:37:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
extern Lisp_Object get_where_is_cache();
^
keymap.h:39:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
extern Lisp_Object get_where_is_cache_keymaps();
^
```
It was fixed by specifying 'void` as the parameters of the above functions.
=> Fixes for the compilation warnings. Closes #672.

rust_src/remacs-sys/lib.rs, rust_src/src/data.rs, rust_src/src/keymap.rs, src/keymap.c, test/rust_src/src/keymap-tests.el
Ported the `get_keymap` C function. Closes #668.
Notes:
- Other parts of `keymap.rs` needed to be updated by removing the now unneeded `unsafe` blocks.
- I had to also update `data.rs` which also uses `get_keymap`.
- Tested working by making temporary lisp tests.
- Initially used Rust labels but refactored it so there are no more nested loops.
=> Ported get_keymap C function

rust_src/remacs-sys/lib.rs, rust_src/src/keymap.rs, src/keymap.c, test/rust_src/src/keymap-tests.el
Some notes that I am unsure of and need guidance with:
- The ported functions needed the `map_keymap_function_t` typedef declared in C, so what i did was I declared a similar type on the Rust side with:
```rust
type map_keymap_function_t =
unsafe extern "C" fn(Lisp_Object, Lisp_Object, Lisp_Object, *const c_void);
```
- I used Rust `c_void` in place of C's `void`.
- I also used `ptr::null_mut()` in place of `NULL`.
As always, thanks for the help!
=> Ported map_keymap and map-keymap functions with tests.

Makefile.in
The generated `remacs.service` file was broken. The `ExecStart` and `ExecStop` were wrongly set (with an `r` character).
```
[Unit]
Description=remacs text editor
Documentation=info:remacs man:remacs(1) https://gnu.org/software/emacs/
[Service]
Type=simple
ExecStart=r/output/bin/remacs --fg-daemon
ExecStop=r/output/bin/remacsclient --eval "(kill-emacs)"
Environment=SSH_AUTH_SOCK=%t/keyring/ssh
Restart=on-failure
[Install]
WantedBy=default.target
```
=> Fix remacs renaming in systemd service

rust_src/remacs-sys/lib.rs, rust_src/src/process.rs, src/process.c, src/process.h, test/rust_src/src/process-tests.el
I ported `process-inherit-coding-system-flag` to Rust. This addresses issue #644.
I ran the following code in Remacs:
```
(defvar myproc (start-process "test" nil "ls"))
(equal nil (process-inherit-coding-system-flag myproc)) ;; => t
(set-process-inherit-coding-system-flag myproc t)
(equal t (process-inherit-coding-system-flag myproc)) ;; => t
```
I can add this to a proper test in test/rust_src/src/process-tests.el if that's useful.
=> Port process-inherit-coding-system-flag to Rust

rust_src/remacs-sys/lib.rs, rust_src/src/keymap.rs, src/keymap.c, test/rust_src/src/keymap-tests.el
This took me awhile mostly because of the casting to `voidfuncptr` as stated [here](https://github.com/Wilfred/remacs/issues/684#issuecomment-371837539).
After a lot of trial and error and researching I found that the solution is to use `std::mem::transmute` as shown [here](https://doc.rust-lang.org/std/mem/fn.transmute.html#examples) which worked out great.
There is a caveat though:
> Turning a pointer into a function pointer. This is not portable to machines where function pointers and data pointers have different sizes.
Not sure if this concerns our project or not. By machines they may refer to different OSs? Should we be concerned?
Thanks!
=> Ported map-keymap-internal and map_keymap_internal functions with tests.

lisp/version.el
I was going to file some bug reports and I realized the version information was inaccurate.
As an aside, how can I get Remacs to load this change? I made the change to `remacs/lisp/version.el`, but `emacs-version` is loaded from `remacs/nextstep/Remacs.app/Contents/Resources/lisp/version.el.gz`. Is there a fast and/or easy way to get the changed file to recompile or whatever?
=> Make emacs-version report Remacs

rust_src/Cargo.lock, rust_src/remacs-macros/Cargo.toml, rust_src/remacs-macros/function.rs, rust_src/remacs-macros/lib.rs
I'd like to play around with the metaprogramming bits, and I found it hard to find documentation for the old quote/syn versions we are using. So I upgraded, and tried to adjust the code accordingly.
My first real PR, so please be gentle :-). Totally willing to make adjustments, of course. (It would be nice to avoid the `syn::TypeFoo(syn::Type::Foo {` stuff, for starters.
=> Update syn (to 0.13.1) and quote (to 0.5), adjust macro definitions.

rust_src/remacs-sys/lib.rs, rust_src/src/cmds.rs, src/cmds.c
but not internal_self_insert (yet)
this fixes #652 
I'm planning to port function internal_self_insert of cmds.c next
=> port the self-insert-command

rust_src/remacs-lib/docfile.rs, rust_src/remacs-macros/function.rs, rust_src/src/editfns.rs, rust_src/src/eval.rs, rust_src/src/hashtable.rs, rust_src/src/lists.rs, rust_src/src/math.rs, rust_src/src/time.rs
This allows slice references to be the sole argument for a lisp_fn function without requiring them to be mutable. I think there's a case to be made for banning mutable slice references entirely, but `run_hook_with_args_internal` actually does modify its argument array.
=> Allow lisp_fn slice arguments to be immutable

.travis-cerrors.sh, .travis.yml, rust_src/Cargo.toml, rust_src/remacs-macros/lib.rs, rust_src/src/lib.rs
This is like #715, but includes testing code to make sure a `compile_error!` is attributed to itself rather than the macro.
=> Restore proper line number attributions for lisp_fn errors

.clang-format, admin/gitmerge.el, admin/make-tarball.txt, doc/lispref/files.texi, etc/NEWS, lisp/autoinsert.el, lisp/files.el, lisp/mpc.el, lisp/newcomment.el, lisp/progmodes/cperl-mode.el, lisp/progmodes/idlwave.el, lisp/textmodes/reftex-ref.el, nt/INSTALL.W64, src/lcms.c, test/src/lcms-tests.el
This brings a few commits over from upstream Emacs. The previous common commit:
```
$ git merge-base origin/master upstream/master    
c0af83b6ccf2dab9a515dd7f52eb9d4500275ae3
```
looks like it was previously on a branch that merged into master. I've tried to take a commit that was clearly on the `master` branch, to make things simpler in future. I think this is why I had a few merge conflicts in files that haven't changed in Remacs, such as lcms.c.
This only brings in a few extra commits, but I hope this makes future merges easier.
=> Update from upstream GNU Emacs

rust_src/src/cmds.rs
Just like the C code we ported it from.
In my defense, I just blindly copied this code from Sean, and didn't
double-check it. Fixes #742
=> Rust's ranges are exclusive of the last value

rust_src/build.rs, rust_src/remacs-macros/lib.rs, rust_src/src/buffers.rs, rust_src/src/chartable.rs, rust_src/src/editfns.rs, rust_src/src/eval.rs, rust_src/src/eval_macros.rs, rust_src/src/ffi.rs, rust_src/src/floatfns.rs, rust_src/src/fns.rs, rust_src/src/functions.rs, rust_src/src/keymap.rs, rust_src/src/lisp.rs, rust_src/src/marker.rs, rust_src/src/obarray.rs, rust_src/src/remacs_sys.rs, rust_src/src/time.rs, rust_src/src/vectors.rs
Closes #706.
This is the mechanical rename part of the change, leaving out the significant clean-up that's possible once `Lisp_Object` is removed.
=> Merge Lisp_Object and LispObject into a new LispObject type.

rust_src/src/obarray.rs, test/rust_src/src/obarray-tests.el
We rely on check_obarray to verify that a value is an obarray. That
function assumed the argument was a vector (it used an unchecked
functions inappropriately).
This caused intern and mapatoms to crash when called with non-obarray
arguments.
Also fix an issue with intern where it assumed a non-vector means it
should use the global obarray, whereas it should only the global
obarray when called with nil.
Add tests for all these cases.
Fixes #731.
=> Fix obarray checks in intern and mapatoms

rust_src/src/eval.rs, test/rust_src/src/eval-tests.el
Addresses #758.
Cause of the issue:
When a hook's value is a single function, C behaviour is to call that function. To check if the value is a function, C code uses `FUNCTIONP`. There was a mistake at this part in ported Rust code and because of that `'(lambda () (+ 1 1))` is treated as a list of functions and this leads to the error `Invalid function: lambda`
Since `run-hooks` takes a symbol as an argument, I couldn't use `let` construct in tests. I used `setq` and `makunbound`. Is this an acceptable usage?
=> run-hooks should accept a symbol evaluating to a function

CONTRIBUTING.md, rust_src/admin/pre-commit
I guess not formatting code with `rustfmt` is a common beginner mistake. Hence added some explanatory text.
=> Add checks for eassert and emacs_abort in pre-commit hook

rust_src/src/casefiddle.rs
they do not have surrounding spaces around them
=> Follow GNU Emacs document style for em-dashes:

rust_src/src/minibuf.rs, rust_src/src/remacs_sys.rs, src/minibuf.c
trying to find a way to return `static Lisp_Object minibuf_prompt`.
this is my first issue. i'm still exploring the project.
=> Port minibuffer-depth and minibuffer-prompt #626

.travis.yml
All we're checking is that we get a compile error when we should. We
don't need a full build for this, and it's adding ~20 minutes to our
build time.
=> Don't run a full build at the C errors stage

rust_src/src/dired.rs, src/dired.c, test/rust_src/src/dired-tests.el
I've got a new&improved file-attributes (and directory-files) that works good on not(windows) but am seeing some Windows problems. And my ability to debug non-trivial stuff on Windows is limited (as I'm not able to build Remacs on my Windows sys yet).
But in the meantime here is file-attributes-lessp.  Seems not to cause any more ```make check``` fails on Linux and Windows (Appveyor). Was tested earlier on MacOS and I assume it's ok but lets see Travis results.
=> Rust dired file-attributes-lessp

rust_src/src/windows.rs, src/window.c
I've been having some trouble porting `set_window_prev/next_buffers`.
After running make, I get
```
cargo build --release --manifest-path ../rust_src/Cargo.toml
Compiling remacs v0.1.0 (file:///home/brian/mygit/remacs/rust_src)
warning: static item is never used: `Sset_window_prev_buffers`
--> src/windows.rs:777:1
|
777 | #[lisp_fn]
| ^^^^^^^^^^
|
= note: #[warn(dead_code)] on by default
= note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)
warning: static item is never used: `Sset_window_next_buffers`
--> src/windows.rs:796:1
|
796 | #[lisp_fn]
| ^^^^^^^^^^
|
= note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info) …
```
=> Add set_window_prev_buffers, set_window_next_buffers, window_prev_buffers, and window_next buffers

test/rust_src/src/data-tests.el
`(describe-function 'rename-buffer)` errors, apparently due to the
inability of `subr-lang` to handle `rename-buffer`.
=> Add passing and failing subr-lang tests

rust_src/src/process.rs, rust_src/src/threads.rs, src/process.c, src/thread.c
Closes #750 and #797.
I'm not sure if I ported `current-thread` correctly. Should the return type be `ThreadStateRef` instead of `LispObject`? I wrote `LispObject` only because that is what `LispObject::tag_ptr()` returns.
=> Port process-coding-system, process-thread, current-thread, and thread--blocker.

docker/ubuntu/32bit/Dockerfile, docker/ubuntu/32bit/config.yaml, docker/ubuntu/Dockerfile, docker/ubuntu/config.yaml
Added missing dependencies (libclang-dev, clang, libxt-dev) to the ubuntu Dockerfiles. Fixes https://github.com/Wilfred/remacs/issues/791 and https://github.com/Wilfred/remacs/issues/788 for docker ubuntu builds.
Perhaps the clang dependency isn't needed (?) when adding compiler flags as decribed in https://github.com/Wilfred/remacs/issues/788, but this fixes the 'stdbool.h not found' error (https://github.com/Wilfred/remacs/issues/791 and second part of https://github.com/Wilfred/remacs/issues/788) for now.
=> ubuntu docker dependencies

rust_src/src/windows.rs, src/window.c
The non-lisp-defun C function `window_parameter` already existed so I added `_defun` to this rust function like I saw a couple other places in the codebase. Is this the right way to do it?
Closes #832
=> Port the window-parameter lisp function to Rust

test/rust_src/src/data-tests.el
Variables defined in Rust aren't documented properly. These are some
tiny reproducing examples.
See https://github.com/Wilfred/remacs/issues/876.
=> Add variable-documentation tests

README.md
On Ubuntu 18.04 libgnutls-dev is libgnutls28-dev
EDIT: Also added clang as a requirement. See commit https://github.com/Wilfred/remacs/pull/888/commits/6ffa657e9ada212588e50a268777c5126d366011
EDIT2: Added libxt-dev, a required dependency.
=> libgnutls-dev changes to libgnutls28-dev

rust_src/remacs-lib/docfile.rs, test/rust_src/src/data-tests.el
The logic here was inverted. We don't want to report per keyboard or
per buffer variables as globals, but we do still want to put their
docstrings into the DOC file.
Fixes #876
=> don't skip the doc strings of kboard or per_buffer variables

rust_src/src/fileio.rs, src/fileio.c, test/rust_src/src/fileio-tests.el
This is a strange function, right? It could easily be written in Lisp,
but I guess it's implemented as a primitive for efficiency. It's
mostly used as a predicate in calls to `sort'.
=> Port car-less-than-car

README.md
I found a couple typos in the README as well as a couple unclear sentences so I fixed those up.
There were also a couple lines that had trailing whitespace so I also removed that
=> Fix a few typos or unclear sentences in the README

rust_src/src/casefiddle.rs, src/casefiddle.c, src/lisp.h
A lot of work is still being done in C, but all the exposed Lisp stuff is in Rust.
=> Port remaining casefiddle Lisp functions

rust_src/src/data.rs, src/data.c, test/rust_src/src/data-tests.el
The implemention is a little different, but it shouldn't matter. I
couldn't think of a better way to test it, since the function is by
definition platform-dependent.
=> Port byteorder

README.md
```bash
remacs$ ./autogen.sh
Checking Rust toolchain install ...
info: syncing channel updates for 'nightly-2018-09-09-x86_64-unknown-linux-gnu'
info: latest update on 2018-09-09, rust version 1.30.0-nightly (0198a1ea4 2018-09-08)
info: downloading component 'rustc'
info: downloading component 'rust-std'
info: downloading component 'cargo'
info: downloading component 'rust-docs'
info: installing component 'rustc'
info: installing component 'rust-std'
info: installing component 'cargo'
info: installing component 'rust-docs'
...
```
=> rustup-toolchain will be installed when running ./autogen.sh

rust_src/src/casefiddle.rs, src/casefiddle.c, src/lisp.h
I actually wanted to port the casify lisp functions, but somebody beat me to it so I tried doing `casify_word`.
I'm not sure I'm using the correct functions to deal with this, so a review would be much appreciated.
=> Port casify_word

rust_src/build.rs
Hello! I'm a long time emacs user, familiar with C (though not yet expert at rust or emacs internals), and thought remacs was a very interesting idea, and thought perhaps I'd try to take a crack at porting some builtins.
While attempting to get it to build on my machine, I found I needed to add these `.rustified_enum` calls. Without them, the
```rust
.default_enum_style(bindgen::EnumVariation::ModuleConsts)
```
in `build.rs` causes module wrappers for `gnutls_ctype_target_t` and `gnutls_fips_mode_t` and `gnutls_gost_paramset_t` to be created, e.g. the `bindgen`-generated `bindings.rs` contains
```rust
pub mod gnutls_ctype_target_t {
pub type Type = u32;
pub const GNUTLS_CTYPE_CLIENT: Type = 0;
pub const GNUTLS_CTYPE_SERVER: Type = 1;
pub const GNUTLS_CTYPE_OURS: Type = 2;
pub const …
```
=> Also .rustified_enum some more recently introduced enums from gnutls

configure.ac, src/dispextern.h, src/dispnew.c, src/emacs-icon.h, src/frame.c, src/frame.h, src/image.c, src/window.c
After merging #885, the x-toolkit has only four options now.
* no
* yes or gtk (means gtk2 or gtk3)
* gtk2
* gtk3
This PR delete the `no` option. After merging this, the `HAVE_X_WINDOWS` and
`USE_GTK` will equal in value. They will just be same in Remacs.
=> delete `no` option for `--with-x-toolkit`

CONTRIBUTING.md, lib-src/hashdir/src/main.rs, rust_src/remacs-lib/docfile.rs, rust_src/remacs-lib/files.rs, rust_src/remacs-macros/lib.rs, rust_src/src/base64.rs, rust_src/src/buffers.rs, rust_src/src/data.rs, rust_src/src/decompress.rs, rust_src/src/dired_unix.rs, rust_src/src/eval.rs, rust_src/src/keymap.rs, rust_src/src/lisp.rs, rust_src/src/lread.rs, rust_src/src/marker.rs, rust_src/src/minibuf.rs, rust_src/src/multibyte.rs, rust_src/src/obarray.rs, rust_src/src/process.rs, rust_src/src/remacs_sys.rs, rust_src/src/str2sig.rs, rust_src/src/strings.rs, rust_src/src/time.rs, rust_src/src/vectors.rs, rust_src/src/windows.rs
Based on https://github.com/Wilfred/remacs/pull/913
As is evident, I take a pretty granular approach when it comes to commits for this kind of thing.
After this, there are just a few big classes of Clippy errors/warnings remaining. One of them has to do marking any function that dereferences a raw pointer as `unsafe`. Another one has to with changing `self` arguments to `&self`, or maybe the other way around. Those seem like bigger changes that should be discussed first, so I didn't do them.
=> More Clippy!!

configure.ac, src/frame.c, src/keyboard.c, src/window.h, src/xfns.c, src/xterm.c, src/xterm.h
Always use toolkit scrollbar in any GUI config. Simplify the code.
Depends on #919.
=> Delete toolkit scroll bar option

rust_src/src/lread.rs, src/buffer.h, src/lread.c, test/rust_src/src/lread-tests.el
What would 
```c
struct infile
{
/* The input stream.  */
FILE *stream;
/* Lookahead byte count.  */
signed char lookahead;
/* Lookahead bytes, in reverse order.  Keep these here because it is
not portable to ungetc more than one byte at a time.  */
unsigned char buf[MAX_MULTIBYTE_LENGTH - 1];
} *infile;
```
look like in rust ?
=> port eval-region

rust_src/src/hashtable.rs
Add a `HashLookupResult` which defines `Missing` and `Found`.
=> Replace C style hash::lookup implementation with a more idiomatic Rust version.

rust_src/src/chartable.rs, rust_src/src/fonts.rs, rust_src/src/lisp.rs, rust_src/src/lists.rs, rust_src/src/obarray.rs
Followup to #708. Makes most single-item tuple structs using `#[repr(C)]` use `transparent` instead to guarantee C interop in function signatures or structs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wilfred/remacs/967)
=> More #[repr(transparent)] coverage

rust_src/Cargo.lock, rust_src/Cargo.toml, rust_src/src/data.rs, rust_src/src/eval_macros.rs, rust_src/src/lib.rs, rust_src/src/syntax.rs, src/data.c
Closes #798 and #809. Two tests had unexpected failures locally, but they seem unrelated.
This introduces [if_chain](https://docs.rs/if_chain/0.1.3/if_chain/) as a direct dependency (it was already pulled in transitively) to maintain some more Rustic expression flow in the match, but if that doesn't look like something that'll probably be used elsewhere, it can be dropped and either an early return or duplication of the `else` arm can be used.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wilfred/remacs/960)
=> Port default-value and default-boundp

rust_src/src/hashtable.rs, rust_src/src/remacs_sys.rs, src/fns.c, src/lisp.h
Move related methods together.
Make hash_clear visible so bindgen can work with it.
=> Touch hashtable.rs

default.nix
This PR adds a nix expression, which can used to set up a shell environment for development.
=> add default.nix expression to assist development using nix

rust_src/src/buffers.rs, rust_src/src/casefiddle.rs, rust_src/src/editfns.rs, rust_src/src/eval.rs, rust_src/src/lread.rs, rust_src/src/windows.rs
As I understand it, the lisp_fn macro converts Rust return values to
Lisp values. In particular, the unit () is converted to nil. Thus a
function that returns only Qnil might as well return nothing at all,
since the ultimate Lisp function will return nil anyway.
=> Cut unnecessary nil returns

rust_src/src/dispnew.rs
close #1029 
I think the problem with this is that elisp only knows nil and not nil.
=> don't use bool for lisp_fn arguments

rust_src/src/dispnew.rs
Reverts Wilfred/remacs#1030
The problem was I did not invert the boolean. Tossing out the bool and going back to LispObject solves the problem but is heavy handed.
=> Revert "don't use bool for lisp_fn arguments"

rust_src/src/cmds.rs, rust_src/src/data.rs, rust_src/src/eval.rs, rust_src/src/keymap.rs, rust_src/src/symbols.rs, src/data.c
Nothing special here, just trying out @shaleh 's porting script. I set the inputs types of these functions to `LispSymbolRef`, which required a few changes in other places.
=> Port set, set-default

autogen.sh
Before:
The active version is not the required one and is set via directory override:\n\tnightly-2018-11-02-x86_64-unknown-linux-gnu (directory override for '/home/wilfred/projects/remacs')Run 'rustup override unset' in this directory.
After:
The active version is not the required one and is set via directory override:
nightly-2018-11-02-x86_64-unknown-linux-gnu (directory override for '/home/wilfred/projects/remacs')
Run 'rustup override unset' in this directory.
=> Ensure that \n is treated as a newline

rust_src/src/base64.rs, rust_src/src/buffers.rs, rust_src/src/casefiddle.rs, rust_src/src/category.rs, rust_src/src/lists.rs
Add a unchecked tails and cars iterator which directly maps to
```
while CONSP(obj)
{
// use obj
obj = XCDR(obj);
}
```
=> Clean up earlier porting efforts.

rust_src/src/data.rs, src/data.c
This is a new function, that we haven't merged yet. I want to make the rollup easier.
```c
DEFUN ("logcount", Flogcount, Slogcount, 1, 1, 0,
doc: /* Return population count of VALUE.
This is the number of one bits in the two's complement representation
of VALUE.  If VALUE is negative, return the number of zero bits in the
representation.  */)
(Lisp_Object value)
{
CHECK_NUMBER (value);
EMACS_INT v = XINT (value) < 0 ? -1 - XINT (value) : XINT (value);
return make_number (EMACS_UINT_WIDTH <= UINT_WIDTH
? count_one_bits (v)
: EMACS_UINT_WIDTH <= ULONG_WIDTH
? count_one_bits_l (v)
: count_one_bits_ll (v));
}
```
=> port logcount

rust_src/src/editfns.rs, rust_src/src/minibuf.rs, src/editfns.c
Return a tuple instead of using C style pointer returns.
=> Remove exported C 'find_field'. Replace with updated Rust version.

rust_src/src/lib.rs
This resolves the clippy failure.
=> Allow unsafe in functions.

rust_src/admin/rustize-emacs, rust_src/src/eval.rs, src/eval.c
This updates `rustize-emacs` to handle `UNEVALLED`, with `unwind-protect` as a test case. While porting, I noticed a few places where `LispObject` could be `LispCons`, so I updated those too.
=> Port unwind-protect, minor changes

rust_src/src/windows.rs, src/window.c, test/rust_src/src/windows-tests.el
Commit includes a Rust implementation of `window-new-normal`, removal
of the old C function and defsubr for same, and a test to assure
`windows-new-normal` correctly returns the value set by
`set-window-new-normal`.
Closes #1048
=> Port `window-new-normal` to Rust

rust_src/remacs-lib/docfile.rs, test/lib-src/make-docfile-tests.el
Emacs stores the function usage without the function name like this:
(fn foo &rest args)
When we find a function with an explicit `usage:` section we keep
the part after the function name.
If the function does not have usage we generate it.
=> Fix 'usage' in docstrings.

rust_src/admin/rustize-emacs, rust_src/src/eval.rs, src/eval.c
`rustize-emacs` wasn't correctly handling the min args of MANY-valued functions, like run-hook functions.
=> Port some run-hook functions, rustize-emacs

.travis.yml
Hopefully this will give us more information when a failure happens. Like the charpos <= bytepos error.
=> Enable RUST_BACKTRACE for builds.

rust_src/src/buffers.rs, rust_src/src/fns.rs, rust_src/src/lisp.rs, rust_src/src/marker.rs, rust_src/src/multibyte.rs, src/fns.c, src/lisp.h
Move to local equal methods. Add `equal` for Overlay and Marker.
`LispMarkerRef` now owns the transition to its subtypes similar to how `LispVectorlike` works. The original `LispObject` calls still exist but they delegate down.
=> Port misc equal to Rust.

rust_src/src/buffers.rs
For some reason it crashes on OSX.
Closes #1132
=> Use a static RNG instead of thread_rng.

README.md
This should prevent encountering any issues with a missing `stdbool.h`, as seen in issue #1140.
=> Add clang-7 to list of dependencies

rust_src/src/windows.rs, src/window.c, test/rust_src/src/windows-tests.el
Hi! I ported `window-parameters`. This PR will close #1104.
BTW, `rust_src/Cargo.lock` is edited (by `cargo`?) after `make`.
`Cargo.lock` had also changed if I run `make` on `master` branch, so I decided not to add this change to my PR.
Is it OK?
=> Port window-parameters

rust_src/src/fns.rs, rust_src/src/lib.rs, rust_src/src/lisp.rs, rust_src/src/numbers.rs
This came out of the discussion in #1148 where the return value for `load-average`/`load_average` ended up being too generic.
This lets us return `Vec<LispNumber>` from a function we want to expose to lisp.
=> Implement From<Vec<T>> for LispObject and convert one use

rust_src/src/frames.rs
Fixes users not being able to close frames, solving issue #1134
=> Mark delete-frame as interactive

rust_src/src/base64.rs, test/rust_src/src/base64-tests.el
The function receives a no-line-break argument but the function which
performs the encoding expects a line-break argument, making us do the
opposite of documented behaviour.
Negate the variable when passing it along and add a test to verify
this behaviour.
We have to use a long string so the inputs are a bit awkward. I tried to make it better with `make-list` but it's still not great.
This fixes #1125
=> Fix base64-encode-string NO-LINE-BREAK behaviour

rust_src/src/marker.rs
The implmentation of `From<LispMakerRef> for LispObject` transmutes the memory which means we fail to tag the pointer. As the receiver expects it to be tagged it thinks it's a `Lisp_Symbol` which confuses the code quite a bit and can cause assertions to fail.
Fix that and tag the pointer as "misc". Since this is fixed, make use of the conversions by accepting and returning `LispMarkerRef` in some lisp function implementations which would crash `temacs` before this change.
---
This tagging error is the cause of #1167 and it's probably related to  #820 and #1145 though I can't be positive as those are assertions on the contents.
=> Fix LispMarkerRef tagging when converting to LispObject and make some use of it

rust_src/src/editfns.rs, rust_src/src/time.rs, src/editfns.c, test/rust_src/src/editfns-tests.el
This doesn't go as far as #965 and leaves the types untouched. It also makes use of the new `From` magic and returns `Vec<LispNumber>` for the time. :man_dancing: 
The carries from one unit to the next in `time_add` and `time_subtract` have been ported to a more explicit and rusty form, but this does mean we've introduced conditionals which are not there in the C version. I don't know how big a deal this actually is, but we could have a version that casts e.g. `(us > 1_000_000 as u32)` so we can add/multiply 0 and 1.
=> Port time-add, time-subtract and time-less-p

rust_src/src/buffers.rs, rust_src/src/data.rs, rust_src/src/dired_unix.rs, rust_src/src/dispnew.rs, rust_src/src/editfns.rs, rust_src/src/eval.rs, rust_src/src/floatfns.rs, rust_src/src/fns.rs, rust_src/src/fonts.rs, rust_src/src/frames.rs, rust_src/src/lisp.rs, rust_src/src/lists.rs, rust_src/src/numbers.rs, rust_src/src/symbols.rs, rust_src/src/syntax.rs, rust_src/src/vectors.rs
This allows for getting rid of a lot of manual casts, giving a Lispier feel while providing the same compiler guarantees. I don't think there are any runtime penalties for doing it this way.
Ideally everything would be generic, and we wouldn't need manual casts at all except maybe for weird cases (eg `LispObject::from_float`). In particular, it would be nice if there was a way to make all the `Fc_functions` generic.
=> Make cons and equality functions generic

rust_src/src/buffers.rs, rust_src/src/data.rs, rust_src/src/dispnew.rs, rust_src/src/eval.rs, rust_src/src/eval_macros.rs, rust_src/src/floatfns.rs, rust_src/src/fns.rs, rust_src/src/keyboard.rs, rust_src/src/math.rs, rust_src/src/symbols.rs, rust_src/src/syntax.rs
This reduces the number of symbols that need to be passed around.
=> Use specific error macros instead of xsignal

rust_src/src/base64.rs, rust_src/src/buffers.rs, rust_src/src/strings.rs, src/fns.c
This build on top of #1168 so the rustification part doesn't conflict. We start by fixing the logic in `byte_pos_addr` which did not take the gap/gpt into account and thus would return wrong values when we tried to use it after `move_gap_both`.
After moving the implementation for `base64-{decode,encode}-region` there were no more base64 functions in C, so we no longer need the `extern "C"` or unsafe buffer operations. We can move those support functions to use Rust types. We can also remove functions meant to figure out how much to preallocate.
=> Port base64-decode-region and base64-encode-region and rustify support code

rust_src/src/frames.rs, src/frame.c
This is my first attempt with the remacs project.
I think I got the implementation straight but when I launch remacs it says `Symbol’s function definition is void: frame-after-make-frame`.
=> Port frame-after-make-frame (fix #1106)

rust_src/src/buffers.rs, rust_src/src/keymap.rs, rust_src/src/process.rs, rust_src/src/syntax.rs, rust_src/src/window_configuration.rs, rust_src/src/windows.rs
The function name exported to C is the Rust name with a capital F
prepended. If this is not the intended name then we have to set the
correct name with `c_name`. The value of `name` is _NOT_ used because
it could be an invalid C (and Rust) name like for instance `+`.
Also, this PR begins standardizing our naming. Rust versions of a DEFUN
which cannot use the orignal name are named `foo_lisp`.
=> If the Rust name is not the expected C name we have to set it.

rust_src/src/minibuf.rs, rust_src/src/obarray.rs, test/rust_src/src/obarray-tests.el
This is the GNU Emacs behavior.
=> Intern should only accept strings

rust_src/src/buffers.rs, rust_src/src/data.rs, rust_src/src/editfns.rs, rust_src/src/eval.rs, rust_src/src/floatfns.rs, rust_src/src/fns.rs, rust_src/src/frames.rs, rust_src/src/keymap.rs, rust_src/src/lists.rs, rust_src/src/lread.rs, rust_src/src/obarray.rs, rust_src/src/process.rs, rust_src/src/windows.rs
Calls to LispObject::cons would look cleaner if they were just
tuples. We can have the compiler do the conversions for us. This makes
the code a little Lispier.
Note that the conversion works recursively, so nested pairs don't need
to be handled as a special case.
=> impl From<(S, T)> for LispObject

src/Makefile.in
This ensures that the generated bindings are updated whenever a symbol is blacklisted, for example.
=> Add dependency to remacs-bindings sources for generated-bindings

rust_src/src/lib.rs, rust_src/src/xfaces.rs, src/dispextern.h, src/xfaces.c
1. I'd like to give that `53` a meaningful constant name, but I don't know what this value means
2. I can't get this to compile, even when cleaning the build. This is the first time I'm making a new Rust module in Remacs so I probably missed something:
```
/usr/bin/ld: composite.o: in function `Fclear_composition_cache':
/home/roeyd/src/remacs/src/composite.c:700: undefined reference to `Fclear_face_cache'
/usr/bin/ld: fontset.o: in function `free_realized_fontsets':
/home/roeyd/src/remacs/src/fontset.c:1327: undefined reference to `Fclear_face_cache'
collect2: error: ld returned 1 exit status
```
=> Port clear-face-cache (fix #1164)

rust_src/src/buffers.rs, rust_src/src/casefiddle.rs, rust_src/src/crypto/mod.rs, rust_src/src/data.rs, rust_src/src/eval.rs, rust_src/src/ffi.rs, rust_src/src/fns.rs, rust_src/src/fonts.rs, rust_src/src/keymap.rs, rust_src/src/lisp.rs, rust_src/src/lists.rs, rust_src/src/minibuf.rs, rust_src/src/process.rs, rust_src/src/time.rs, rust_src/src/windows.rs
This change complements 6f4ac71065. I wanted to make it possible to
destructure arbitrary conses, as in
```rust
let (a, (b, c)) = obj.into();
```
but I don't think that's possible. A little destructuring is possible
though, and this replaces `as_tuple` with it. `as_cons_or_error` is
also cut along the way, in favor of `From`/`into`.
A few style changes have also been made wrt destructuring, like
```
-        self.valcell.as_cons_or_error().cdr()
+        let (_, d) = self.valcell.into();
+        d
```
I think this is a little more in keeping with the Rust mindset of
exhaustive matching -- the caller explicitly acknowledges that there
is another value in the cons cell, and that that value is being thrown
away.
=> Add tuple conversions, cut as_tuple and as_cons_or_error

lib-src/Makefile.in
Fixes #1135.
This prevents occasional build failures when settings custom RUSTFLAGS. The build failure occured when executing below command on a clean checkout.
./autogen.sh && ./configure --enable-rust-debug && \ make -j4 RUSTFLAGS="-C target-cpu=native" all
=> Quote RUSTFLAGS in lib-src/Makefile.in

rust_src/Cargo.lock, rust_src/Cargo.toml.in, rust_src/src/base64.rs
From version 0.10.0, base64 crate does not provide the function to
wrap encoded string in the expected line length and delete whitespaces
from the string to be decoded. The former has pulled into the
line-wrap crate and the latter can be achived by a short code.
Closes #1241.
=> Update to latest base64 crate (0.10.0)

rust_src/src/process.rs, src/process.c
Provide a Rust implementation for the interrupt-process
function.
This implements #1195.
Signed-off-by: Sanchayan Maity <maitysanchayan@gmail.com>
=> Port interrupt-process

rust_src/src/editfns.rs, rust_src/src/eval.rs, rust_src/src/fns.rs, src/eval.c, src/lisp.h
Port the `record_unwind_protect` set of functions.
These changes are split from #1233.
=> Port record_unwind_protect functions

configure.ac, rust_src/Cargo.lock, rust_src/Cargo.toml.in, rust_src/src/emacs.rs, rust_src/src/keyboard.rs, src/keyboard.c
This requires conditional compilation based on whether the platform is windows (for `is_daemon()`).
Not sure what's the best way to do that. I think this works but I didn't test it on windows.
=> Port command-error-or-default-function

rust_src/src/frames.rs, rust_src/src/windows.rs, src/window.c
This closes #1188.
Because the vast majority of functions used in `window_body_{height,width}` are macros, I had to add quite a few functions to `LispWindowRef`.
=> Port window-body-height and window-body-width

rust_src/src/keyboard.rs
=> Fix mistake in porting `error-command-default-function`

rust_src/src/windows.rs
Closes #1293.
Also added a a comment specifying which c function `LispWindowOrSelected` replaces, which should clarify which type should be used where.
=> Fix type error in window-buffer

configure.ac
Explicitly check whether `pkg-config` can be found in path. I have a suspicion this check is superfluous, as `PKG_PROG_PKG_CONFIG` may already check for this. I have yet to confirm this, though.
This should close #611.
=> Throw an error if pkg-config is missing

rust_src/Cargo.lock, rust_src/Cargo.toml.in, rust_src/src/buffers.rs, rust_src/src/data.rs, rust_src/src/lib.rs, rust_src/src/symbols.rs
Adds `as_buffer_objfwd()` which returns an `Option<Lisp_Buffer_Objfwd>`.
This simplifies the common use of the object. Remove `if_chain` now
that the code is simpler.
=> Refactor buffer_objfwd support.

lisp/help-fns.el, test/rust_src/src/data-tests.el
The aim of this PR is to resolve #822.
As pointed out in comments on previous issues, `subr-lang` gets `wrong-type-argument` for adviced builtin function because `subr-lang` expects an argument is a subroutine but adviced function is no longer regarded as subroutine.
This small patch tries to fix this error giving to `subr-lang` the real function definition being detached from advice part. This seems already prepared in the function concerned using `help-fns--analyze-function`.
=> Fix error on describe-function for adviced builtin function

rust_src/src/lisp.rs, rust_src/src/windows.rs
This makes it simpler to modify the underlying pointer of an `ExternalPtr`. Instances of `replace_ptr` have been replaced with the new methods where appropriate.
Closes #1317.
=> Add transformation methods to ExternalPtr

docker/fedora/Dockerfile, docker/fedora/config.yaml
Also, yum is deprecated and may be removed in Fedora 30, so change to
dnf.
Closes #1327
=> Added necessary libraries for fedora

rust_src/src/lread.rs, src/buffer.h, src/lread.c
I was on the fence on whether or not to port `readbyte_from_stdio`, as it relies on a lot of behaviour that's expressed much more elegantly in c than rust, but I think i managed to get it right.
Closes #1300.
=> Port get-file-char

rust_src/src/buffers.rs, rust_src/src/dired.rs, rust_src/src/dired_unix.rs, rust_src/src/lib.rs, rust_src/src/multibyte.rs, rust_src/src/obarray.rs, rust_src/src/strings.rs, rust_src/src/symbols.rs
Making a draft to make sure I get the type right before I make functions use it. I'm not exactly sure which conversions should do the type check and which should skip them.
Also, when converting this to a LispSymbolRef, should I throw an error if the value is a string or something else?
EDIT: Just discovered `Fmake_sym` exists. Should I use that for converting strings to symbols?
Will close #1209.
=> Add LispSymbolOrString type

README.md
Now that Remacs is a separate organisation (see #1245), the README needs updating.
=> Update Travis badge for new GitHub URL

configure.ac, rust_src/Cargo.lock, rust_src/Cargo.toml.in, rust_src/remacs-lib/Cargo.toml, rust_src/remacs-lib/files.rs, rust_src/src/buffers.rs, rust_src/src/numbers.rs, test/rust_src/src/buffers-tests.el, test/rust_src/src/numbers-tests.el
My strategy is:
* Use `ThreadRng` if we can. This is automatically reseeded after generating 32MiB random data. I have not tested this code on macOS yet. I just checked only it could be built using travis. May crash on runtime. Please help testing if you are interested in :wink:
* In `number.rs`, there are something to do with the seed, which seems to not changed for `ThreadRng`. We continue to use static variable.
Closes #1242.
=> Update to latest rand crate

rust_src/src/base64.rs, rust_src/src/buffers.rs, rust_src/src/callproc.rs, rust_src/src/decompress.rs, rust_src/src/editfns.rs
The C function takes two pointers. In Rust, we can return a tuple instead. Less unsafe is good.
=> Refactor validate region

rust_src/src/lread.rs
Using the same value for intspec as the original [C-code DEFUN sixth argument](https://github.com/emacs-mirror/emacs/blob/master/src/lread.c#L2161).
Closes #1346
=> Added intspec for eval_region

rust_src/src/base64.rs, rust_src/src/buffers.rs, rust_src/src/decompress.rs, rust_src/src/editfns.rs, rust_src/src/marker.rs
Convert the core logic to methods on `LispBufferRef`.
Update exported functions to use the methods.
This removes a few more unsafes. No logic was touched.
=> Refactor charpos and bytepos functions.

README.md
The README now includes a link to the Gitter channel
=> Update README to include link to Gitter Channel

rust_src/remacs-lib/docfile.rs, rust_src/src/lib.rs
Resolves #1402 
This lint rule has been renamed in the latest Clippy version
These are the only two references to the name I found by grepping the code.
I tested it by temporarily removing these lines and running `cargo clippy` again. This caused cognitive complexity warnings to be displayed when they weren't before.
I'm pretty new to both Rust and the emacs source code, but this is something I figured I could handle :).
=> Replace `clippy::cyclomatic_complexity` with `clippy::cognitive_complexity`

rust_src/src/buffers.rs, rust_src/src/filelock.rs, rust_src/src/lib.rs, src/filelock.c, test/rust_src/src/filelock-tests.el
Fixes #928. Introduces `filelock.rs`.
Added `LispBufferRef.modified_since_save()` since grepping for `SAVE_MODIFF` in `src` shows it could be useful in other places as well.
=> Port lock-buffer and unlock-buffer

rust_src/admin/rustize-emacs
While working on #1408 I noticed the script crashes when run on [`set_window_hscroll`][swh] in [`src/window.c`][window], because the [`<comment>`][regex] group consumes both the comment before the function definition and the two comments inside the function body. This fixes the crash by making the `<comment>` group reluctant instead of greedy, so it consumes as few characters as possible.
[regex]: https://github.com/remacs/remacs/blob/master/rust_src/admin/rustize-emacs#L140
[swh]: https://github.com/remacs/remacs/blob/master/src/window.c#L519
[window]: https://github.com/remacs/remacs/blob/master/src/window.c
=> Make rustize-emacs function comment regex reluctant

rust_src/src/windows.rs, src/window.c, test/rust_src/src/windows-tests.el, test/src/window-tests.el
Fixes #1408.
I'm not sure I have the best approach to computing `hscroll_max`, but at least it should be safe - unless I'm mistaken, the only reason the `try_from` call should fail is if `MOST_POSITIVE_FIXNUM` is too big for an `isize`. `std::cmp::max(MOST_POSITIVE_FIXNUM, isize::max_value())` is not applicable since the two arguments are of different types.
=> Port set-window-hscroll

rust_src/src/buffers.rs, rust_src/src/windows.rs
When I saw #1421 it occured to me I hadn't done this for get_text_property when I ported it.
I also took the opportunity to fix one of the Clippy warnings I've been getting for an unnecessary type conversion in windows.rs.
=> Fix Rust usage of get_text_property

rust_src/src/lib.rs, rust_src/src/minibuf.rs, rust_src/src/strings.rs, src/minibuf.c
Closes #1224.
The way the creation of the string for the format invocation feels a bit messy. We really need a nicer way to create `LispStringRef`s from rust strings.
=> Port read-buffer

rust_src/src/buffers.rs, src/buffer.c
Closes #433 
This didn't break any tests locally, so I think I'm on the right track with this function. The compiler caught most of my mistakes :).
=> Port overlay_recenter

rust_src/src/lread.rs, src/lisp.h, src/lread.c
These three small functions are pretty much direct translations of their C counterparts, and all make use of the much more complex `read_filtered_event` C function, which is definitely beyond my ability to port. 
Closes #923 .
=> Port read-chars, read-event and read-char-exclusive from lread.c

rust_src/src/windows.rs, src/window.c, test/rust_src/src/windows-tests.el
Fixes https://github.com/remacs/remacs/issues/1429
Currently lacks tests due to problem with ert: it doesn't actually change `window-pixel-width-before-size-change` during tests (probably because tests doesn't change frame and thus `window-size-change-functions` not invoked).
=> Port window-pixel-width-before-size-change (and -height)

.travis.yml, configure.ac, rust_src/Cargo.toml.in, rust_src/build.rs, rust_src/src/lib.rs, rust_src/src/lisp.rs, rust_src/src/xdisp.rs, src/xdisp.c, test/rust_src/src/xdisp-tests.el
Fixes #1014.
Added Rust features for all of the Emacs checking flags while at it. Let me know if they are not (going to be) needed and I’ll just drop them.
=> [WIP] Port trace-redisplay

rust_src/src/charset.rs, rust_src/wrapper.h, src/charset.c, src/tempcharset.h
Closes #1174 
I _think_ I'm on the right path here, but I'm not quite there yet. I get this error when running `make`, when trying to link/build the temacs executable:
```
.././rust_src/target/release/libremacs.a(remacs-d72c4967c380b3d7.remacs.254nx1kb-cgu.3.rcgu.o): In function `Fclear_charset_maps':
remacs.254nx1kb-cgu.3:(.text.Fclear_charset_maps+0x4): undefined reference to `temp_charset_work'
```
Part of the reason for this might be that I added a new header file to contain the `temp_charset_work` struct, as I mentioned in issue #1174. I've referenced it in charset.c and wrapper.h, should I add it somewhere else?
=> Port clear-charset-maps

rust_src/src/frames.rs, src/frame.c
I noticed this function was fairly simple and only called functions which already had been ported to Rust, so I made an attempt at porting it.
=> Port get_frame_param

rust_src/Cargo.lock, rust_src/Cargo.toml.in, rust_src/src/editfns.rs, rust_src/src/filelock.rs, src/filelock.c, test/rust_src/src/filelock-tests.el
As a sort of continuation to #1394.
Some notes/caveats:
- No Windows support. remacs doesn’t seem to build on Windows right now so there’s no way to test :frowning_face: 
- Adds dependency to [systemstat crate](https://crates.io/crates/systemstat), which provides, among other things, system boot time information.
- Some duplication between `filelock.c` and `filelock.rs` remain, pending ports of [`lock_file`](https://github.com/remacs/remacs/blob/fa68c1f5df7834d063e8b9c7b8a262178e0059ca/src/filelock.c#L640), [`unlock_file`](https://github.com/remacs/remacs/blob/fa68c1f5df7834d063e8b9c7b8a262178e0059ca/src/filelock.c#L725), [`unlock_all_files`](https://github.com/remacs/remacs/blob/fa68c1f5df7834d063e8b9c7b8a262178e0059ca/src/filelock.c#L742) and …
=> Port file-locked-p

rust_src/build.rs, rust_src/src/lib.rs, rust_src/src/xsettings.rs, rust_src/wrapper.h, src/tempxsettings.h, src/xsettings.c
There wasn't a xsettings.rs file yet, so I created it. Since both of these functions relied on static C variables, I went with the same strategy I used for clear-charset-maps, creating a new `tempxsettings.h` header to contain their `extern` declarations.
This closes #1458 and also ports font-get-normal-system-font, which was very similar.
=> Port font-get-system-font and font-get-system-normal-font

rust_src/src/multibyte.rs, rust_src/src/strings.rs
I'd like to have a `PartialEq` implementation that works for both `&str` and `&String`, but `PartialEq<Deref<Target=str>>` doesn't do the trick. Any advice here would be appreciated.
And feel free to bikeshed about the test name.
Closes #1291.
=> Add comparisons for lisp strings with native types

rust_src/Cargo.lock, rust_src/remacs-lib/Cargo.toml, rust_src/remacs-lib/lib.rs, rust_src/remacs-macros/Cargo.toml, rust_src/remacs-macros/function.rs, rust_src/remacs-macros/lib.rs
Partially addresses https://github.com/remacs/remacs/issues/1244
It doesn't look like we can upgrade `syn` for the `remacs-util` crate because newer versions of `syn` use `proc_macro` internally and trying to use these related functions outside of `#[proc_macro_attribute]` or `#[proc_macro_derive(...)]` will give us a `procedural macro API is used outside of a procedural macro` error. (We manually parse `lisp_fn` attributes in `remacs_lib/docfile.rs`)
The older version of `syn` (0.11.11) for the `remacs-util` crate works because it uses a fork of `nom` called [synom](https://crates.io/crates/synom) instead of relying on `proc_macro`; as far as I can see, this fork was abandoned a couple of years ago. 
TL;DR: this PR updates `syn` where-ever possible (only `remacs-macros`); we may need to …
=> update syn for `remacs-macros`

rust_src/src/base64.rs, rust_src/src/buffers.rs, rust_src/src/character.rs, rust_src/src/cmds.rs, rust_src/src/data.rs, rust_src/src/editfns.rs, rust_src/src/fns.rs, rust_src/src/indent.rs, rust_src/src/multibyte.rs
Lots of functions have been made methods on Codepoint instead. There
have also been made lots of changes around the code to accommodate the
type change.
Closes #1501.
=> Make Codepoint a newtype

rust_src/remacs-lib/files.rs, rust_src/src/buffers.rs
likely because C owns the threads. Fixes MacOS compilation.
Closes: #1425
=> ThreadRNG causes segfaults.

rust_src/src/fonts.rs
Closes #1444.
Fixes segmentation fault introduced in https://github.com/remacs/remacs/pull/1371
and discussed in https://github.com/remacs/remacs/issues/1444
The crash was caused by applying an unnecessary tag to the pointer during `LispFontSpecRef -> LispObject` conversion
evaluate `(list-fonts (font-spec :size 10))`
Remacs returns `nil` (or crashes without this fix)
Emacs returns a list of fonts
=> fix list-fonts

src/.gdbinit, src/print.c
This fixes the "Attempt to write memory outside diversion session"
error that you would get when using the `pp` alias.
In order to preserve the correct replay behavior, rr must prevent the
state of the program from diverging from the recording. Thus, any gdb
command which writes to memory (or might do so), needs to be coerced
into writing to freshly-allocated memory which can then be thrown away
after the command is done. rr allocates a 'diversion area' where
writes can happen when we call a function, but it doesn't do this when
we merely try to set a variable (don't ask me why).
=> make pretty-printing work in rr

rust_src/src/dired_unix.rs
`file-attributes` constructed its return value using a `vec`, storing the `LispObjects` on the heap. When a GC cycle was triggered mid-function, those heap-stored objects were missed by the GC mark phase, leading to https://github.com/remacs/remacs/issues/845. This change ensures these values are visible on the stack.
=> Take LispObjects off the heap in file-attributes

rust_src/src/frames.rs, src/frame.c, src/frame.h
This is an attempt to port `make-frame-invisible` to rust.
=> Port make-frame-invisible.

rust_src/src/windows.rs, src/window.c, test/rust_src/src/windows-tests.el
Hello!
I've added a port for `window-scroll-bar-width` and `window-scroll-bar-height`. Most of the logic was already ported, which made it more straightforward.
=> Port window-scroll-bar-width and window-scroll-bar-height

rust_src/src/frames.rs, src/frame.c, src/frame.h, src/lisp.h
Original function to port, which is defined in the ticket/issue #1418 `last-nonminibuffer-frame` is accessing a global static variable (which afaik is not accessible from Rust, cause it's sort of fileprivate)
This variable is used in other functions as well, so in order to port this function, I decided to firstly, port the static variable itself.
All accesses to it in C are done via function calling (get/set) to Rust
=> [Frame] migrate static variable last_non_minibuffer_frame from C to Rust

rust_src/src/buffers.rs, rust_src/src/fonts.rs, rust_src/src/lib.rs, rust_src/src/libm.rs, rust_src/src/lisp.rs, rust_src/src/marker.rs, rust_src/src/terminal.rs, rust_src/src/threads.rs, rust_src/src/vectors.rs
Almost every single transmute is used to cast between versions of `ExternalPtr<T>` and we can instead get away with casting the pointers.
I wondered about using some `From<ExternalPtr<U>> for ExternalPointer<T>` but these are behind a type check so I thought maybe it shouldn't be *that* easy to convert between them.
This handles most of #1208 although there are a couple of uses which aren't nearly as clear-cut which I've left out of this PR.
=> Remove most uses of transmute

rust_src/src/windows.rs, src/window.c, src/window.h, test/rust_src/src/windows-tests.el
Hello,
I hope it closes issue #1441 
I have 2 questions.
1. Do I have to port `DEFVAR_LISP ("window-configuration-change-hook", ...)` using `defvar_lisp!`?
2. I've deleted `static` from C source codes. Is it a correct idea?
* I want to call `run_window_configuration_change_hook` C function from Rust source code
=> Port run-window-configuration-change-hook (#1441)

.travis.yml, autogen.sh
autogen.sh was failing because the return value of rustup was not
understood which lead to an assertion.
Simplify the rustup and rust version checks by using `rustup toolchain list` which does not try to update the system.
Closes: #1549
=> Detect when rustup upgrades the local Rust version.

rust_src/src/data.rs
scroll-up-aggressively and scroll-down-aggressively are defined as
type fraction, so their values must be between 0.0 and 1.0
inclusive. Because the test was inverted, we were accepting only
values outside that range.
fixes #1574
=> inverted test when checking that the new value is in the right range

docker/fedora/Dockerfile, docker/ubuntu/32bit/Dockerfile, docker/ubuntu/Dockerfile, docker/ubuntu/cosmic/Dockerfile
This commit changes all Dockerfiles so that the nightly-2020-04-07 Rust toolchain is used since this was changed in 5b59c0f77113a1330853cff077a08f00c8f7fc88. Without this change, building via a Docker container fails due to the Rust toolchain incompatibility.
=> Modifies Dockerfiles for current Rust toolchain
